export const affiliateLinks: Record<string, string> = {
  'prohealth-nmn': 'https://www.amazon.com/s?k=ProHealth+Longevity+NMN+Pro&tag=michaelregeer-20',
  'tru-niagen': 'https://www.amazon.com/s?k=ChromaDex+Tru+Niagen&tag=michaelregeer-20',
  'double-wood-nmn': 'https://www.amazon.com/s?k=double+wood+nmn&tag=michaelregeer-20',
  'dexcom-stelo': 'https://www.stelo.com/?ref=longevitylab',
  'libre3': 'https://www.amazon.com/s?k=libre3&tag=michaelregeer-20',
  'carlson-omega3': 'https://www.amazon.com/s?k=Carlson+Elite+Omega-3&tag=michaelregeer-20',
  'nordic-omega3': 'https://www.amazon.com/s?k=Nordic+Naturals+Ultimate+Omega&tag=michaelregeer-20',
  'mito-red-1500': 'https://www.amazon.com/s?k=Mito+Red+Light+MitoPRO+1500&tag=michaelregeer-20',
  'lumebox': 'https://www.lumebox.com/?ref=longevitylab',
  'whoop-4': 'https://join.whoop.com/?ref=longevitylab',
  'oura-gen3': 'https://ouraring.com/?ref=longevitylab',
  'garmin-fenix7': 'https://www.amazon.com/s?k=Garmin+Fenix+7&tag=michaelregeer-20',
  'fisetin-lifeext': 'https://www.amazon.com/s?k=Life+Extension+Fisetin&tag=michaelregeer-20',
  'function-health': 'https://www.functionhealth.com/?ref=longevitylab',
  'insidetracker': 'https://www.insidetracker.com/?ref=longevitylab',
  'gaia-rhodiola': 'https://www.amazon.com/s?k=Gaia+Herbs+Rhodiola+Rosea&tag=michaelregeer-20',
  'ksm66-ashwagandha': 'https://www.amazon.com/s?k=Ixoreal+%2F+KSM-66+KSM-66+Ashwagandha&tag=michaelregeer-20',
  'jarrow-nac': 'https://www.amazon.com/s?k=Jarrow+Formulas+N-Acetyl+Cysteine+NAC&tag=michaelregeer-20',
  'jarrow-pqq': 'https://www.amazon.com/s?k=Jarrow+Formulas+PQQ+Pyrroloquinoline+Quinone&tag=michaelregeer-20',
  'jarrow-rala': 'https://www.amazon.com/s?k=Jarrow+Formulas+R-Alpha+Lipoic+Acid&tag=michaelregeer-20',
  'jarrow-tmg': 'https://www.amazon.com/s?k=Jarrow+Formulas+TMG+Trimethylglycine&tag=michaelregeer-20',
  'jarrow-ubiquinol': 'https://www.amazon.com/s?k=Jarrow+Formulas+Ubiquinol+CoQ10&tag=michaelregeer-20',
  'lifeext-caakg': 'https://www.amazon.com/s?k=Life+Extension+Ca-AKG+Calcium+Alpha-Ketoglutarate&tag=michaelregeer-20',
  'livon-vitamin-c': 'https://www.amazon.com/s?k=LivOn+Labs+Vitamin+C+Liposomal&tag=michaelregeer-20',
  'now-taurine': 'https://www.amazon.com/s?k=NOW+Foods+Taurine&tag=michaelregeer-20',
  'primeadine-spermidine': 'https://www.oxfordhealthspan.com/MICHAEL54679',
  'pure-mag-glycinate': 'https://www.amazon.com/s?k=Pure+Encapsulations+Magnesium+Glycinate&tag=michaelregeer-20',
  'thorne-berberine': 'https://amzn.to/3SJ1nap',
  'thorne-creatine': 'https://amzn.to/4p9D4Pe',
  'thorne-d3k2': 'https://amzn.to/44djRCp',
  'thorne-quercetin': 'https://amzn.to/4y68Q3p',
  'thorne-resveratrol': 'https://www.amazon.com/s?k=resveratrol+supplement&tag=michaelregeer-20',
  'resveratrol': 'https://www.amazon.com/s?k=resveratrol+supplement&tag=michaelregeer-20',
  'thorne-zinc': 'https://www.amazon.com/s?k=zinc+picolinate+supplement&tag=michaelregeer-20',
  'hostdefense-lionsmane': 'https://www.amazon.com/s?k=Host+Defense+hostdefense-lionsmane&tag=michaelregeer-20',
  'ndga': 'https://www.amazon.com/s?k=Double+Wood+NDGA+Nordihydroguaiaretic+Acid&tag=michaelregeer-20',
  'lithium-orotate': 'https://www.amazon.com/s?k=Seeking+Health+Lithium+Orotate+Microdose&tag=michaelregeer-20',
  'joovv-solo-3': 'https://joovv.com/?ref=longevitylab',
  'biomax-300': 'https://www.amazon.com/s?k=PlatinumLED+BioMax+300&tag=michaelregeer-20',
  'sunlighten-mpulse': 'https://share.sunlighten.com/MichaelRegeer',
  'clearlight-sanctuary': 'https://www.awin1.com/cread.php?awinmid=101701&awinaffid=2967749&ued=https%3A%2F%2Finfraredsauna.com%2F',
  'serenelife-sauna': 'https://www.amazon.com/s?k=SereneLife+Portable+Infrared+Sauna&tag=michaelregeer-20',
  'the-plunge-pro': 'https://www.coldplunge.com/?ref=longevitylab',
  'morozko-forge': 'https://morozkoforge.com/?ref=longevitylab',
  'chest-freezer-guide': 'https://longevitylab.com/guides/chest-freezer-cold-plunge',
  'theragun-pro-6': 'https://www.therabody.com/?ref=longevitylab',
  'hypervolt-2-pro': 'https://www.awin1.com/cread.php?awinmid=25761&awinaffid=2967749&ued=https%3A%2F%2Fhyperice.com%2F',
  'renpho-r3': 'https://www.amazon.com/s?k=renpho+r3&tag=michaelregeer-20',
  'melatonin-timed-release': 'https://www.amazon.com/s?k=Life+Extension+Melatonin+Timed-Release&tag=michaelregeer-20',
  'blublox-glasses': 'https://www.blublox.com/?ref=longevitylab',
  'citicoline-cognizin': 'https://www.amazon.com/s?k=Double+Wood+Citicoline+Cognizin&tag=michaelregeer-20',
  'bacopa-monnieri': 'https://www.amazon.com/s?k=Himalaya+Bacopa+Monnieri&tag=michaelregeer-20',
  'seed-ds01': 'https://seed.com/?ref=longevitylab',
  'thorne-meriva-curcumin': 'https://www.amazon.com/s?k=curcumin+phytosome+meriva&tag=michaelregeer-20',
  'now-curcubrain': 'https://www.amazon.com/s?k=now+curcubrain&tag=michaelregeer-20',
  'mitopure-timeline': 'https://www.timelinenutrition.com/?ref=longevitylab',
  'urolithin-a-doublewood': 'https://www.amazon.com/s?k=urolithin+a+doublewood&tag=michaelregeer-20',
  'almost-heaven-barrel': 'https://www.amazon.com/s?k=Almost+Heaven+Saunas+Independence+4-Person+Barrel+Sauna&tag=michaelregeer-20',
  'harvia-heater-kit': 'https://www.amazon.com/s?k=Harvia+Harvia+KIP+Electric+Sauna+Heater+Kit&tag=michaelregeer-20',
  'newtowne-hyperbaric': 'https://www.newtownehyperbarics.com/?ref=longevitylab',
  'amazon-mild-hyperbaric-chamber': 'https://www.amazon.com/s?k=portable+mild+hyperbaric+oxygen+chamber&tag=michaelregeer-20',

  // ─── Aliases: same product, different slug used in article content ────
  'garmin-fenix-7': 'https://www.amazon.com/s?k=Garmin+Fenix+7&tag=michaelregeer-20',
  'jarrow-r-ala': 'https://www.amazon.com/s?k=jarrow+r+ala&tag=michaelregeer-20',
  'life-extension-fisetin': 'https://www.amazon.com/s?k=life+extension+fisetin&tag=michaelregeer-20',
  'host-defense-lions-mane': 'https://www.amazon.com/s?k=host+defense+lions+mane&tag=michaelregeer-20',
  'nordic-naturals': 'https://www.amazon.com/s?k=nordic+naturals&tag=michaelregeer-20',
  'primeadine': 'https://www.oxfordhealthspan.com/MICHAEL54679',
  'seed-synbiotic': 'https://seed.com/?ref=longevitylab',
  'theragun-pro': 'https://www.therabody.com/?ref=longevitylab',
  'thorne-dk2': 'https://amzn.to/44djRCp',
  'thorne-ala': 'https://www.amazon.com/s?k=alpha+lipoic+acid+supplement&tag=michaelregeer-20',
  'thorne-mag-glycinate': 'https://www.amazon.com/s?k=magnesium+glycinate+supplement&tag=michaelregeer-20',
  'thorne-taurine': 'https://www.amazon.com/s?k=taurine+supplement&tag=michaelregeer-20',

  // ─── Wearables / fitness tech ──────────────────────────────────────────
  'apple-watch-s9': 'https://www.amazon.com/s?k=Apple+Watch+Series+9&tag=michaelregeer-20',
  'apple-watch-ultra-2': 'https://www.amazon.com/s?k=Apple+Watch+Ultra+2&tag=michaelregeer-20',
  'fitbit-charge6': 'https://www.amazon.com/s?k=Fitbit+Charge+6&tag=michaelregeer-20',
  'eight-sleep': 'https://www.eightsleep.com/?ref=longevitylab',
  'loop-quiet': 'https://www.amazon.com/s?k=Loop+Quiet+earplugs&tag=michaelregeer-20',
  'manta-mask': 'https://www.amazon.com/s?k=Manta+Sleep+Mask&tag=michaelregeer-20',

  // ─── Diagnostics / testing services ─────────────────────────────────────
  'levels-health': 'https://www.levelshealth.com/?ref=longevitylab',
  'marek-health': 'https://marekhealth.com/?ref=longevitylab',
  'elysium-basis': 'https://www.elysiumhealth.com/?ref=longevitylab',
  'elysium-index': 'https://www.elysiumhealth.com/?ref=longevitylab',
  'trudiagnostic': 'https://www.trudiagnostic.com/?ref=longevitylab',
  'viome': 'https://www.viome.com/?ref=longevitylab',
  'zoe': 'https://joinzoe.com/?ref=longevitylab',
  'prolon': 'https://prolonlife.com/?ref=longevitylab',

  // ─── Recovery equipment ──────────────────────────────────────────────────
  '2xu-compression': 'https://amzn.to/4p0DUxk',
  'air-relax': 'https://www.amazon.com/s?k=air+relax&tag=michaelregeer-20',
  'normatec-3': 'https://www.amazon.com/s?k=normatec+3&tag=michaelregeer-20',
  'triggerpoint-grid': 'https://www.amazon.com/s?k=triggerpoint+grid&tag=michaelregeer-20',
  'flexpulse': 'https://www.bemergroup.com/?ref=longevitylab',
  'higherdose-pemf': 'https://www.higherdose.com/?ref=longevitylab',
  'float-lab': 'https://www.thefloatlab.com/?ref=longevitylab',
  'samadhi-tank': 'https://www.samadhitank.com/?ref=longevitylab',

  // ─── Fitness equipment ───────────────────────────────────────────────────
  'bowflex-552': 'https://www.amazon.com/s?k=bowflex+552&tag=michaelregeer-20',
  'concept2-rowerg': 'https://www.amazon.com/s?k=concept2+rowerg&tag=michaelregeer-20',
  'rep-pr4000': 'https://www.repfitness.com/?ref=longevitylab',

  // ─── Supplements — Amazon-linked ─────────────────────────────────────────
  'bulk-creatine': 'https://amzn.to/4p9D4Pe',
  'dihydroberberine': 'https://www.amazon.com/s?k=dihydroberberine+glucovantage&tag=michaelregeer-20',
  'dw-berberine': 'https://www.amazon.com/s?k=dw+berberine&tag=michaelregeer-20',
  'it-berberine': 'https://amzn.to/3SJ1nap',
  'jarrow-ashwagandha': 'https://www.amazon.com/s?k=jarrow+ashwagandha&tag=michaelregeer-20',
  'jarrow-bacopa': 'https://www.amazon.com/s?k=jarrow+bacopa&tag=michaelregeer-20',
  'le-dk2': 'https://amzn.to/44djRCp',
  'le-ubiquinol': 'https://amzn.to/3SJ1HG9',
  'magtein': 'https://amzn.to/4eMdUm0',
  'momentous-ashwagandha': 'https://www.livemomentous.com/?ref=longevitylab',
  'nootropics-depot-lions-mane': 'https://nootropicsdepot.com/?ref=longevitylab',
  'now-ashwagandha': 'https://amzn.to/4fi37A5',
  'now-ps': 'https://amzn.to/4vNpp2M',
  'now-quercetin': 'https://amzn.to/4y68Q3p',
  'on-creatine': 'https://www.amazon.com/s?k=on+creatine&tag=michaelregeer-20',
  'pterostilbene': 'https://amzn.to/4eZjMqS',
  'qunol-coq10': 'https://www.amazon.com/s?k=qunol+coq10&tag=michaelregeer-20',
  'real-mushrooms-lions-mane': 'https://www.realmushrooms.com/?ref=longevitylab',
  'ritual-synbiotic': 'https://ritual.com/?ref=longevitylab',
  'sr-dk2': 'https://www.amazon.com/s?k=sports+research+vitamin+d3+k2&tag=michaelregeer-20',
  'uc2-collagen': 'https://amzn.to/4y3FNO5',
  'vital-proteins': 'https://amzn.to/4ve8rJF',
  'wonderfeel-youngr': 'https://getwonderfeel.com/?ref=longevitylab',
  'donotage-spermidine': 'https://donotage.org/?ref=longevitylab',
  'bioptimizers-magnesium': 'https://bioptimizers.com/?ref=longevitylab',
  'biolite-sunlight': 'https://amzn.to/4gWOC61',

  // ─── New products (cardio/sleep/nutrition/stress page linking pass) ────
  'real-mushrooms-reishi': 'https://www.realmushrooms.com/?ref=longevitylab',
  'real-mushrooms-cordyceps': 'https://www.realmushrooms.com/?ref=longevitylab',
  'now-l-theanine': 'https://amzn.to/4eTkTZa',
  'dw-apigenin': 'https://www.amazon.com/s?k=double+wood+apigenin&tag=michaelregeer-20',
  'bulk-glycine': 'https://amzn.to/4y51kGa',
  'now-chromium': 'https://amzn.to/4y6tCQx',
  'now-cinnamon': 'https://amzn.to/3SISFsO',
  'thorne-vitamin-e': 'https://www.amazon.com/s?k=vitamin+e+mixed+tocopherols&tag=michaelregeer-20',
  'now-alcar': 'https://amzn.to/44cg8Fk',
  'now-beta-alanine': 'https://amzn.to/4vntMk8',
  'superbeets': 'https://www.humann.com/?ref=longevitylab',
  'now-sodium-bicarbonate': 'https://amzn.to/4p9EIAo',
  'now-tart-cherry': 'https://amzn.to/4aVExCT',
}
