export const affiliateLinks: Record<string, string> = {
  'prohealth-nmn': 'https://www.amazon.com/dp/B07TNTQ7VV?tag=longevitylab-20',
  'tru-niagen': 'https://www.amazon.com/dp/B07DW75BX3?tag=longevitylab-20',
  'double-wood-nmn': 'https://www.amazon.com/dp/B09BKNHNN8?tag=longevitylab-20',
  'dexcom-stelo': 'https://www.stelo.com/?ref=longevitylab',
  'libre3': 'https://www.amazon.com/dp/B0C1VHRJMP?tag=longevitylab-20',
  'carlson-omega3': 'https://www.amazon.com/dp/B000NV8NKC?tag=longevitylab-20',
  'nordic-naturals': 'https://www.amazon.com/dp/B002CQU564?tag=longevitylab-20',
  'mito-red-1500': 'https://www.amazon.com/dp/B08XYZ123?tag=longevitylab-20',
  'joovv-solo-3': 'https://joovv.com/?ref=longevitylab',
  'biomax-300': 'https://www.amazon.com/dp/B07PLTNJ5V?tag=longevitylab-20',
  'sunlighten-mpulse': 'https://sunlighten.com/?ref=longevitylab',
  'clearlight-sanctuary': 'https://infraredsauna.com/?ref=longevitylab',
  'serenelife-sauna': 'https://www.amazon.com/dp/B07WPDL75Z?tag=longevitylab-20',
  'the-plunge-pro': 'https://www.coldplunge.com/?ref=longevitylab',
  'morozko-forge': 'https://morozkoforge.com/?ref=longevitylab',
  'chest-freezer-guide': 'https://longevitylab.com/guides/chest-freezer-cold-plunge',
  'theragun-pro-6': 'https://www.therabody.com/?ref=longevitylab',
  'hypervolt-2-pro': 'https://hyperice.com/?ref=longevitylab',
  'renpho-r3': 'https://www.amazon.com/dp/B08CMWND5K?tag=longevitylab-20',
  'melatonin-timed-release': 'https://www.amazon.com/dp/B0013OUL8C?tag=longevitylab-20',
  'blublox-glasses': 'https://www.blublox.com/?ref=longevitylab',
  'citicoline-cognizin': 'https://www.amazon.com/dp/B00E5COPB6?tag=longevitylab-20',
  'bacopa-monnieri': 'https://www.amazon.com/dp/B01M4PVDE6?tag=longevitylab-20',
  'seed-ds01': 'https://seed.com/?ref=longevitylab',
}
