export const affiliateLinks: Record<string, string> = {
  'prohealth-nmn': 'https://www.amazon.com/dp/B07TNTQ7VV?tag=michaelregeer-20',
  'tru-niagen': 'https://www.amazon.com/dp/B07DW75BX3?tag=michaelregeer-20',
  'double-wood-nmn': 'https://www.amazon.com/dp/B09BKNHNN8?tag=michaelregeer-20',
  'dexcom-stelo': 'https://www.stelo.com/?ref=longevitylab',
  'libre3': 'https://www.amazon.com/dp/B0C1VHRJMP?tag=michaelregeer-20',
  'carlson-omega3': 'https://www.amazon.com/dp/B000NV8NKC?tag=michaelregeer-20',
  'nordic-omega3': 'https://www.amazon.com/dp/B002CQU564?tag=michaelregeer-20',
  'mito-red-1500': 'https://www.amazon.com/dp/B08XYZ123?tag=michaelregeer-20',
  'lumebox': 'https://www.lumebox.com/?ref=longevitylab',
  'whoop-4': 'https://join.whoop.com/?ref=longevitylab',
  'oura-gen3': 'https://ouraring.com/?ref=longevitylab',
  'garmin-fenix7': 'https://www.amazon.com/dp/B0B4F1J64C?tag=michaelregeer-20',
  'fisetin-lifeext': 'https://www.amazon.com/dp/B07T3JC9MX?tag=michaelregeer-20',
  'function-health': 'https://www.functionhealth.com/?ref=longevitylab',
  'insidetracker': 'https://www.insidetracker.com/?ref=longevitylab',
  'gaia-rhodiola': 'https://www.amazon.com/dp/B0013OUMRO?tag=michaelregeer-20',
  'ksm66-ashwagandha': 'https://www.amazon.com/dp/B01N9SF0F8?tag=michaelregeer-20',
  'jarrow-nac': 'https://www.amazon.com/dp/B0013OSOIS?tag=michaelregeer-20',
  'jarrow-pqq': 'https://www.amazon.com/dp/B003UFCG34?tag=michaelregeer-20',
  'jarrow-rala': 'https://www.amazon.com/dp/B0013OUMC4?tag=michaelregeer-20',
  'jarrow-tmg': 'https://www.amazon.com/dp/B0013OSNJU?tag=michaelregeer-20',
  'jarrow-ubiquinol': 'https://www.amazon.com/dp/B003BSAVZW?tag=michaelregeer-20',
  'lifeext-caakg': 'https://www.amazon.com/dp/B0BJLF8R7T?tag=michaelregeer-20',
  'livon-vitamin-c': 'https://www.amazon.com/dp/B00280EJ04?tag=michaelregeer-20',
  'now-taurine': 'https://www.amazon.com/dp/B0013OQH7M?tag=michaelregeer-20',
  'primeadine-spermidine': 'https://www.oxfordhealthspan.com/?ref=longevitylab',
  'pure-mag-glycinate': 'https://www.amazon.com/dp/B07PCMV4GW?tag=michaelregeer-20',
  'thorne-berberine': 'https://www.thorne.com/?ref=longevitylab',
  'thorne-creatine': 'https://www.thorne.com/?ref=longevitylab',
  'thorne-d3k2': 'https://www.thorne.com/?ref=longevitylab',
  'thorne-quercetin': 'https://www.thorne.com/?ref=longevitylab',
  'thorne-resveratrol': 'https://www.thorne.com/?ref=longevitylab',
  'thorne-zinc': 'https://www.thorne.com/?ref=longevitylab',
  'hostdefense-lionsmane': 'https://www.amazon.com/dp/B00MMNUFTU?tag=michaelregeer-20',
  'ndga': 'https://www.amazon.com/dp/B07T3MXKZ8?tag=michaelregeer-20',
  'lithium-orotate': 'https://www.amazon.com/dp/B0015AOUWY?tag=michaelregeer-20',
  'joovv-solo-3': 'https://joovv.com/?ref=longevitylab',
  'biomax-300': 'https://www.amazon.com/dp/B07PLTNJ5V?tag=michaelregeer-20',
  'sunlighten-mpulse': 'https://share.sunlighten.com/MichaelRegeer',
  'clearlight-sanctuary': 'https://infraredsauna.com/?ref=longevitylab',
  'serenelife-sauna': 'https://www.amazon.com/dp/B07WPDL75Z?tag=michaelregeer-20',
  'the-plunge-pro': 'https://www.coldplunge.com/?ref=longevitylab',
  'morozko-forge': 'https://morozkoforge.com/?ref=longevitylab',
  'chest-freezer-guide': 'https://longevitylab.com/guides/chest-freezer-cold-plunge',
  'theragun-pro-6': 'https://www.therabody.com/?ref=longevitylab',
  'hypervolt-2-pro': 'https://hyperice.com/?ref=longevitylab',
  'renpho-r3': 'https://www.amazon.com/dp/B08CMWND5K?tag=michaelregeer-20',
  'melatonin-timed-release': 'https://www.amazon.com/dp/B0013OUL8C?tag=michaelregeer-20',
  'blublox-glasses': 'https://www.blublox.com/?ref=longevitylab',
  'citicoline-cognizin': 'https://www.amazon.com/dp/B00E5COPB6?tag=michaelregeer-20',
  'bacopa-monnieri': 'https://www.amazon.com/dp/B01M4PVDE6?tag=michaelregeer-20',
  'seed-ds01': 'https://seed.com/?ref=longevitylab',
  'thorne-meriva-curcumin': 'https://www.thorne.com/?ref=longevitylab',
  'now-curcubrain': 'https://www.amazon.com/dp/B01N4CH8ZF?tag=michaelregeer-20',
  'mitopure-timeline': 'https://www.timelinenutrition.com/?ref=longevitylab',
  'urolithin-a-doublewood': 'https://www.amazon.com/dp/B09TPCXQZC?tag=michaelregeer-20',
  'almost-heaven-barrel': 'https://www.amazon.com/dp/B08L5NXQXW?tag=michaelregeer-20',
  'harvia-heater-kit': 'https://www.amazon.com/dp/B0813WQXQF?tag=michaelregeer-20',
  'newtowne-hyperbaric': 'https://www.newtownehyperbarics.com/?ref=longevitylab',
  'amazon-mild-hyperbaric-chamber': 'https://www.amazon.com/s?k=portable+mild+hyperbaric+oxygen+chamber&tag=michaelregeer-20',

  // ─── Aliases: same product, different slug used in article content ────
  'garmin-fenix-7': 'https://www.amazon.com/dp/B0B4F1J64C?tag=michaelregeer-20',
  'jarrow-r-ala': 'https://www.amazon.com/dp/B0013OUMC4?tag=michaelregeer-20',
  'life-extension-fisetin': 'https://www.amazon.com/dp/B07T3JC9MX?tag=michaelregeer-20',
  'host-defense-lions-mane': 'https://www.amazon.com/dp/B00MMNUFTU?tag=michaelregeer-20',
  'nordic-naturals': 'https://www.amazon.com/dp/B002CQU564?tag=michaelregeer-20',
  'primeadine': 'https://www.oxfordhealthspan.com/?ref=longevitylab',
  'seed-synbiotic': 'https://seed.com/?ref=longevitylab',
  'theragun-pro': 'https://www.therabody.com/?ref=longevitylab',
  'thorne-dk2': 'https://www.thorne.com/?ref=longevitylab',
  'thorne-ala': 'https://www.thorne.com/?ref=longevitylab',
  'thorne-mag-glycinate': 'https://www.thorne.com/?ref=longevitylab',
  'thorne-taurine': 'https://www.thorne.com/?ref=longevitylab',

  // ─── Wearables / fitness tech ──────────────────────────────────────────
  'apple-watch-s9': 'https://www.amazon.com/dp/B0CHX6QNBP?tag=michaelregeer-20',
  'apple-watch-ultra-2': 'https://www.amazon.com/dp/B0CHX9RJT3?tag=michaelregeer-20',
  'fitbit-charge6': 'https://www.amazon.com/dp/B0CC61CVSD?tag=michaelregeer-20',
  'eight-sleep': 'https://www.eightsleep.com/?ref=longevitylab',
  'loop-quiet': 'https://www.amazon.com/dp/B08KHVXQ26?tag=michaelregeer-20',
  'manta-mask': 'https://www.amazon.com/dp/B07TSCX7BR?tag=michaelregeer-20',

  // ─── Diagnostics / testing services ─────────────────────────────────────
  'levels-health': 'https://www.levelshealth.com/?ref=longevitylab',
  'marek-health': 'https://marekhealth.com/?ref=longevitylab',
  'elysium-basis': 'https://www.elysiumhealth.com/?ref=longevitylab',
  'elysium-index': 'https://www.elysiumhealth.com/?ref=longevitylab',
  'trudiagnostic': 'https://www.trudiagnostic.com/?ref=longevitylab',
  'viome': 'https://www.viome.com/?ref=longevitylab',
  'zoe': 'https://joinzoe.com/?ref=longevitylab',
  'prolon': 'https://prolonlife.com/?ref=longevitylab',

  // ─── Recovery equipment ──────────────────────────────────────────────────
  '2xu-compression': 'https://amzn.to/4p0DUxk',
  'air-relax': 'https://www.amazon.com/dp/B078WGZ8FS?tag=michaelregeer-20',
  'normatec-3': 'https://www.amazon.com/dp/B08X6QJXFV?tag=michaelregeer-20',
  'triggerpoint-grid': 'https://www.amazon.com/dp/B0040EGNIU?tag=michaelregeer-20',
  'flexpulse': 'https://www.bemergroup.com/?ref=longevitylab',
  'higherdose-pemf': 'https://www.higherdose.com/?ref=longevitylab',
  'float-lab': 'https://www.thefloatlab.com/?ref=longevitylab',
  'samadhi-tank': 'https://www.samadhitank.com/?ref=longevitylab',

  // ─── Fitness equipment ───────────────────────────────────────────────────
  'bowflex-552': 'https://www.amazon.com/dp/B001ARYU58?tag=michaelregeer-20',
  'concept2-rowerg': 'https://www.amazon.com/dp/B07CNZ5FKY?tag=michaelregeer-20',
  'rep-pr4000': 'https://www.repfitness.com/?ref=longevitylab',

  // ─── Supplements — Amazon-linked ─────────────────────────────────────────
  'bulk-creatine': 'https://amzn.to/4p9D4Pe',
  'dihydroberberine': 'https://www.amazon.com/s?k=dihydroberberine+glucovantage&tag=michaelregeer-20',
  'dw-berberine': 'https://www.amazon.com/dp/B075SVYK4C?tag=michaelregeer-20',
  'it-berberine': 'https://amzn.to/3SJ1nap',
  'jarrow-ashwagandha': 'https://www.amazon.com/dp/B01N9SF0F8?tag=michaelregeer-20',
  'jarrow-bacopa': 'https://www.amazon.com/dp/B01M4PVDE6?tag=michaelregeer-20',
  'le-dk2': 'https://amzn.to/44djRCp',
  'le-ubiquinol': 'https://amzn.to/3SJ1HG9',
  'magtein': 'https://amzn.to/4eMdUm0',
  'momentous-ashwagandha': 'https://www.livemomentous.com/?ref=longevitylab',
  'nootropics-depot-lions-mane': 'https://nootropicsdepot.com/?ref=longevitylab',
  'now-ashwagandha': 'https://amzn.to/4fi37A5',
  'now-ps': 'https://amzn.to/4vNpp2M',
  'now-quercetin': 'https://amzn.to/4y68Q3p',
  'on-creatine': 'https://www.amazon.com/dp/B0736V6PYW?tag=michaelregeer-20',
  'pterostilbene': 'https://amzn.to/4eZjMqS',
  'qunol-coq10': 'https://www.amazon.com/dp/B00NIB6C6O?tag=michaelregeer-20',
  'real-mushrooms-lions-mane': 'https://www.realmushrooms.com/?ref=longevitylab',
  'ritual-synbiotic': 'https://ritual.com/?ref=longevitylab',
  'sr-dk2': 'https://www.amazon.com/s?k=sports+research+vitamin+d3+k2&tag=michaelregeer-20',
  'uc2-collagen': 'https://amzn.to/4y3FNO5',
  'vital-proteins': 'https://amzn.to/4ve8rJF',
  'wonderfeel-youngr': 'https://getwonderfeel.com/?ref=longevitylab',
  'donotage-spermidine': 'https://donotage.org/?ref=longevitylab',
  'bioptimizers-magnesium': 'https://bioptimizers.com/?ref=longevitylab',
  'biolite-sunlight': 'https://amzn.to/4gWOC61',

  // ─── New products (cardio/sleep/nutrition/stress page linking pass) ────
  'real-mushrooms-reishi': 'https://www.realmushrooms.com/?ref=longevitylab',
  'real-mushrooms-cordyceps': 'https://www.realmushrooms.com/?ref=longevitylab',
  'now-l-theanine': 'https://amzn.to/4eTkTZa',
  'dw-apigenin': 'https://www.amazon.com/s?k=double+wood+apigenin&tag=michaelregeer-20',
  'bulk-glycine': 'https://amzn.to/4y51kGa',
  'now-chromium': 'https://amzn.to/4y6tCQx',
  'now-cinnamon': 'https://amzn.to/3SISFsO',
  'thorne-vitamin-e': 'https://www.thorne.com/?ref=longevitylab',
  'now-alcar': 'https://amzn.to/44cg8Fk',
  'now-beta-alanine': 'https://amzn.to/4vntMk8',
  'superbeets': 'https://www.humann.com/?ref=longevitylab',
  'now-sodium-bicarbonate': 'https://amzn.to/4p9EIAo',
  'now-tart-cherry': 'https://amzn.to/4aVExCT',
}
