export type EvidenceLevel = 'Strong' | 'Moderate' | 'Emerging' | 'Weak'
export type ProductCategory =
  | 'Red Light Therapy'
  | 'Infrared Saunas'
  | 'Cold Plunge & Ice Baths'
  | 'Fitness Trackers & HRV'
  | 'Continuous Glucose Monitors'
  | 'Massage & Recovery'
  | 'NAD+ Precursors'
  | 'Antioxidants & Senolytics'
  | 'Adaptogens'
  | 'Omega Fatty Acids'
  | 'Vitamins & Minerals'
  | 'Mitochondrial Support'
  | 'Blood & Diagnostics'
  | 'Sleep Aids'
  | 'Nootropics & Cognitive'
  | 'Gut & Microbiome'

export type Goal =
  | 'Longevity'
  | 'Energy'
  | 'Sleep'
  | 'Cognitive'
  | 'Cardiovascular'
  | 'Recovery'
  | 'Inflammation'
  | 'Metabolic Health'
  | 'Strength & Muscle'
  | 'Skin & Collagen'

export interface Product {
  id: string
  name: string
  brand: string
  tagline: string
  category: ProductCategory
  goals: Goal[]
  evidenceLevel: EvidenceLevel
  evidenceScore: number
  safetyScore: number
  popularityScore: number
  price: string
  summary: string
  keyBenefits: string[]
  bestFor: string
  affiliateUrl?: string
  reviewSlug?: string   // e.g. 'recovery/best-red-light-therapy-panels-2024'
  reviewLabel?: string  // e.g. 'Read Full Review'
  image?: string
  badge?: 'Best Pick' | 'Runner-Up' | 'Budget' | "Editor's Choice" | 'Premium'
  studyCount?: number
  dosage?: string
  timing?: string
  stacksWith?: string[]
}

export const products: Product[] = [

  // ─── RED LIGHT THERAPY ────────────────────────────────────────────────
  {
    id: 'mito-red-1500',
    name: 'MitoPRO 1500',
    brand: 'Mito Red Light',
    tagline: 'Highest irradiance full-body panel in its class',
    category: 'Red Light Therapy',
    goals: ['Recovery', 'Skin & Collagen', 'Energy', 'Inflammation'],
    evidenceLevel: 'Strong',
    evidenceScore: 88,
    safetyScore: 97,
    popularityScore: 90,
    price: '$599',
    badge: 'Best Pick',
    summary: 'The MitoPRO 1500 delivers 97 mW/cm² irradiance — the highest tested in its price range. True dual-chip 660nm + 850nm wavelengths, zero flicker, 5-year warranty.',
    keyBenefits: ['95+ mW/cm² irradiance', 'True 660nm + 850nm dual-chip', 'No EMF at treatment distance', 'Zero flicker confirmed', '5-year warranty'],
    bestFor: 'Full-body red light therapy sessions at home',
    affiliateUrl: '/go/mito-red-1500',
    reviewSlug: 'recovery/best-red-light-therapy-panels-2024',
    reviewLabel: 'Read Full Panel Review',
    image: 'https://images.unsplash.com/photo-1616279969856-759f316a5ac1?w=400&q=80',
    studyCount: 6000,
  },
  {
    id: 'joovv-solo-3',
    name: 'Solo 3.0',
    brand: 'Joovv',
    tagline: 'Premium modular red light system with app control',
    category: 'Red Light Therapy',
    goals: ['Recovery', 'Skin & Collagen', 'Inflammation'],
    evidenceLevel: 'Strong',
    evidenceScore: 82,
    safetyScore: 97,
    popularityScore: 94,
    price: '$1,199',
    badge: 'Runner-Up',
    summary: 'The original consumer red light brand. Beautiful build, app control, ambient mode, and modular design. Irradiance trails cheaper competitors but the ecosystem is unmatched.',
    keyBenefits: ['App-controlled dosing', 'Modular — connects to other panels', 'Ambient mode for circadian support', 'Premium build quality'],
    bestFor: 'Premium buyers who want the full Joovv ecosystem',
    affiliateUrl: '/go/joovv-solo-3',
    reviewSlug: 'recovery/best-red-light-therapy-panels-2024',
    reviewLabel: 'Read Full Panel Review',
    image: 'https://images.unsplash.com/photo-1616279969856-759f316a5ac1?w=400&q=80',
  },
  {
    id: 'biomax-300',
    name: 'BioMax 300',
    brand: 'PlatinumLED',
    tagline: 'Best small panel — 5 wavelengths, ideal for face & joints',
    category: 'Red Light Therapy',
    goals: ['Skin & Collagen', 'Recovery', 'Inflammation'],
    evidenceLevel: 'Strong',
    evidenceScore: 78,
    safetyScore: 97,
    popularityScore: 82,
    price: '$269',
    badge: 'Budget',
    summary: '5-wavelength panel (630, 660, 810, 830, 850nm) in a compact form factor. Best value for targeted face, joint, or injury treatment.',
    keyBenefits: ['5 therapeutic wavelengths', 'Compact — ideal for face & joints', 'Excellent irradiance for size', 'No prescription required'],
    bestFor: 'Targeted treatment and beginners entering red light therapy',
    affiliateUrl: '/go/biomax-300',
    reviewSlug: 'recovery/best-red-light-therapy-panels-2024',
    reviewLabel: 'Read Full Panel Review',
    image: 'https://images.unsplash.com/photo-1616279969856-759f316a5ac1?w=400&q=80',
  },
  {
    id: 'lumebox',
    name: 'LumeBox',
    brand: 'LumeBox',
    tagline: 'Portable travel red light therapy device',
    category: 'Red Light Therapy',
    goals: ['Skin & Collagen', 'Recovery'],
    evidenceLevel: 'Moderate',
    evidenceScore: 70,
    safetyScore: 96,
    popularityScore: 75,
    price: '$349',
    summary: 'Compact, travel-friendly red light device with 660nm + 850nm. Lower total irradiance than full panels but excellent portability.',
    keyBenefits: ['Travel-sized', 'Rechargeable battery', '660nm + 850nm', 'Lightweight (0.8 lbs)'],
    bestFor: 'Travellers wanting red light on the go',
    affiliateUrl: '/go/lumebox',
    image: 'https://images.unsplash.com/photo-1616279969856-759f316a5ac1?w=400&q=80',
  },

  // ─── INFRARED SAUNAS ──────────────────────────────────────────────────
  {
    id: 'sunlighten-mpulse',
    name: 'mPulse Believe',
    brand: 'Sunlighten',
    tagline: 'Full-spectrum infrared sauna with programmable health protocols',
    category: 'Infrared Saunas',
    goals: ['Cardiovascular', 'Recovery', 'Longevity', 'Inflammation'],
    evidenceLevel: 'Strong',
    evidenceScore: 92,
    safetyScore: 95,
    popularityScore: 88,
    price: '$7,995',
    badge: 'Premium',
    summary: 'The most advanced home infrared sauna. Full-spectrum (near, mid, far IR), SoloCarbon heaters at 95% emissivity, programmable health protocols, and built-in tablet.',
    keyBenefits: ['Full-spectrum: near + mid + far IR', 'Programmable longevity protocols', 'Medical-grade SoloCarbon heaters', 'Best-in-class EMF for the spectrum', 'Built-in tablet & chromotherapy'],
    bestFor: 'Serious longevity optimisers wanting the best full-spectrum sauna',
    affiliateUrl: '/go/sunlighten-mpulse',
    reviewSlug: 'recovery/best-home-saunas-infrared-2024',
    reviewLabel: 'Read Full Sauna Review',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&q=80',
  },
  {
    id: 'clearlight-sanctuary',
    name: 'Sanctuary 2',
    brand: 'Clearlight',
    tagline: 'Ultra-low EMF far-infrared sauna with lifetime heater warranty',
    category: 'Infrared Saunas',
    goals: ['Cardiovascular', 'Recovery', 'Longevity'],
    evidenceLevel: 'Strong',
    evidenceScore: 86,
    safetyScore: 97,
    popularityScore: 84,
    price: '$4,999',
    badge: 'Runner-Up',
    summary: 'The lowest-EMF cabin sauna tested. True Wave II carbon/ceramic heaters, Western red cedar construction, 2-person capacity, lifetime warranty on heaters.',
    keyBenefits: ['Ultra-low EMF & ELF', 'True Wave II heaters', 'Western red cedar', 'Lifetime heater warranty', '2-person capacity'],
    bestFor: 'EMF-sensitive buyers wanting premium far-infrared',
    affiliateUrl: '/go/clearlight-sanctuary',
    reviewSlug: 'recovery/best-home-saunas-infrared-2024',
    reviewLabel: 'Read Full Sauna Review',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&q=80',
  },
  {
    id: 'serenelife-sauna',
    name: 'Portable Infrared Sauna',
    brand: 'SereneLife',
    tagline: 'Affordable portable sauna tent — real benefits, no installation',
    category: 'Infrared Saunas',
    goals: ['Recovery', 'Inflammation'],
    evidenceLevel: 'Moderate',
    evidenceScore: 68,
    safetyScore: 90,
    popularityScore: 85,
    price: '$299',
    badge: 'Budget',
    summary: 'Foldable portable sauna tent reaching 140°F. Entry-level heat therapy without installation. Head-out design limits full-body protocol but real sweating and cardiovascular response occurs.',
    keyBenefits: ['No installation required', 'Sets up in minutes', 'Portable & foldable', 'Reaches 140°F'],
    bestFor: 'Renters or beginners testing infrared sauna benefits',
    affiliateUrl: '/go/serenelife-sauna',
    reviewSlug: 'recovery/best-home-saunas-infrared-2024',
    reviewLabel: 'Read Full Sauna Review',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&q=80',
  },

  // ─── COLD PLUNGE ──────────────────────────────────────────────────────
  {
    id: 'the-plunge-pro',
    name: 'The Plunge Pro',
    brand: 'The Plunge',
    tagline: 'Best all-around cold plunge — chills to 37°F with filtration',
    category: 'Cold Plunge & Ice Baths',
    goals: ['Recovery', 'Energy', 'Cardiovascular', 'Inflammation'],
    evidenceLevel: 'Strong',
    evidenceScore: 88,
    safetyScore: 94,
    popularityScore: 91,
    price: '$4,990',
    badge: 'Best Pick',
    summary: 'Sets the standard for home cold plunge units. Chills to 37°F, built-in filtration keeps water clean for weeks, app-controlled scheduling, insulated body.',
    keyBenefits: ['Chills to 37°F (3°C)', 'Built-in filtration + sanitation', 'App scheduling — pre-chill overnight', 'Insulated to maintain temp', '450 lbs capacity'],
    bestFor: 'Serious cold therapy practitioners wanting a set-and-forget system',
    affiliateUrl: '/go/the-plunge-pro',
    reviewSlug: 'recovery/cold-plunge-ice-bath-review',
    reviewLabel: 'Read Full Cold Plunge Review',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80',
  },
  {
    id: 'morozko-forge',
    name: 'Morozko Forge',
    brand: 'Morozko',
    tagline: 'Coldest plunge on the market — chills to 33°F with ozone filtration',
    category: 'Cold Plunge & Ice Baths',
    goals: ['Recovery', 'Energy', 'Cardiovascular'],
    evidenceLevel: 'Strong',
    evidenceScore: 84,
    safetyScore: 93,
    popularityScore: 78,
    price: '$7,990',
    badge: 'Premium',
    summary: 'The coldest consumer cold plunge available — reaches 33°F with ozone-filtered crystal-clear water. Commercial-grade compressor. Overkill for most, perfect for extreme cold therapy enthusiasts.',
    keyBenefits: ['Coldest on market (33°F)', 'Ozone filtration — crystal clear', 'Commercial-grade compressor', 'Can form actual ice'],
    bestFor: 'Cold therapy enthusiasts wanting maximum cold stimulus',
    affiliateUrl: '/go/morozko-forge',
    reviewSlug: 'recovery/cold-plunge-ice-bath-review',
    reviewLabel: 'Read Full Cold Plunge Review',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80',
  },

  // ─── FITNESS TRACKERS ─────────────────────────────────────────────────
  {
    id: 'whoop-4',
    name: 'WHOOP 4.0',
    brand: 'WHOOP',
    tagline: 'Best-in-class HRV tracking and recovery scoring',
    category: 'Fitness Trackers & HRV',
    goals: ['Recovery', 'Sleep', 'Cardiovascular', 'Longevity'],
    evidenceLevel: 'Strong',
    evidenceScore: 91,
    safetyScore: 99,
    popularityScore: 93,
    price: '$239 + $30/mo',
    badge: 'Best Pick',
    summary: 'The gold standard for recovery and HRV tracking. No screen — every resource goes into sensor accuracy. Daily recovery and strain scores, best-in-class sleep staging.',
    keyBenefits: ['Best HRV accuracy (±4.2ms vs ECG)', 'Daily recovery + strain scores', 'Best sleep staging of any wrist device', 'Skin temp + blood oxygen', '24/7 continuous monitoring'],
    bestFor: 'Serious longevity optimisers focused on recovery and HRV',
    affiliateUrl: '/go/whoop-4',
    reviewSlug: 'wearables/best-fitness-trackers-longevity',
    reviewLabel: 'Read Full Tracker Review',
    image: 'https://images.unsplash.com/photo-1510017098667-27dfc7150acb?w=400&q=80',
  },
  {
    id: 'oura-gen3',
    name: 'Ring Gen 3',
    brand: 'Oura',
    tagline: 'Most accurate sleep tracker — worn as a ring',
    category: 'Fitness Trackers & HRV',
    goals: ['Sleep', 'Recovery', 'Cardiovascular', 'Longevity'],
    evidenceLevel: 'Strong',
    evidenceScore: 89,
    safetyScore: 99,
    popularityScore: 91,
    price: '$299 + $5.99/mo',
    badge: "Editor's Choice",
    summary: 'The most accurate consumer sleep tracker available. Finger-based PPG sensors outperform wrist trackers for sleep staging. Continuous skin temperature detects illness 1–3 days early.',
    keyBenefits: ['Best sleep staging accuracy (74% vs PSG)', '7-day battery life', 'Continuous skin temperature', 'Readiness score', 'Discreet ring form factor'],
    bestFor: 'Sleep quality and recovery tracking without wearing a watch',
    affiliateUrl: '/go/oura-gen3',
    reviewSlug: 'wearables/oura-ring-gen3-review',
    reviewLabel: 'Read Full Oura Review',
    image: 'https://images.unsplash.com/photo-1510017098667-27dfc7150acb?w=400&q=80',
  },
  {
    id: 'garmin-fenix7',
    name: 'Fenix 7',
    brand: 'Garmin',
    tagline: 'Best GPS sports watch with HRV and Body Battery',
    category: 'Fitness Trackers & HRV',
    goals: ['Cardiovascular', 'Recovery', 'Longevity'],
    evidenceLevel: 'Strong',
    evidenceScore: 86,
    safetyScore: 99,
    popularityScore: 89,
    price: '$649',
    badge: 'Runner-Up',
    summary: 'Premium GPS watch with serious health tracking — HRV Status, Body Battery recovery score, VO2 max estimation, and 14-day battery. No subscription required.',
    keyBenefits: ['HRV Status (4-week baseline)', 'Body Battery recovery system', 'GPS + multi-sport tracking', '14-day battery life', 'No subscription'],
    bestFor: 'Athletes wanting GPS + longevity health tracking in one device',
    affiliateUrl: '/go/garmin-fenix7',
    reviewSlug: 'wearables/best-fitness-trackers-longevity',
    reviewLabel: 'Read Full Tracker Review',
    image: 'https://images.unsplash.com/photo-1510017098667-27dfc7150acb?w=400&q=80',
  },

  // ─── CGM ──────────────────────────────────────────────────────────────
  {
    id: 'dexcom-stelo',
    name: 'Stelo',
    brand: 'Dexcom',
    tagline: 'First FDA-cleared CGM for non-diabetics — no prescription needed',
    category: 'Continuous Glucose Monitors',
    goals: ['Metabolic Health', 'Longevity', 'Energy'],
    evidenceLevel: 'Strong',
    evidenceScore: 88,
    safetyScore: 98,
    popularityScore: 86,
    price: '$99/month',
    badge: 'Best Pick',
    summary: 'The Dexcom Stelo is the first CGM cleared by the FDA specifically for non-diabetics. No prescription, 14-day wear, MARD of 7.8%, and the best app for metabolic pattern recognition.',
    keyBenefits: ['No prescription required', 'FDA-cleared for non-diabetics', '14-day sensor life', 'MARD 7.8% accuracy', 'Time-in-range + trend analysis'],
    bestFor: 'Non-diabetics wanting metabolic insights without a prescription',
    affiliateUrl: '/go/dexcom-stelo',
    reviewSlug: 'wearables/best-continuous-glucose-monitors',
    reviewLabel: 'Read Full CGM Review',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&q=80',
  },

  // ─── MASSAGE & RECOVERY ───────────────────────────────────────────────
  {
    id: 'theragun-pro-6',
    name: 'Pro Gen 6',
    brand: 'Theragun',
    tagline: 'Professional percussive therapy — deepest amplitude available',
    category: 'Massage & Recovery',
    goals: ['Recovery', 'Inflammation'],
    evidenceLevel: 'Moderate',
    evidenceScore: 82,
    safetyScore: 97,
    popularityScore: 93,
    price: '$599',
    badge: 'Best Pick',
    summary: '16mm amplitude and 60 lbs stall force — the professional standard for percussive therapy. Rotating arm, OLED screen, Bluetooth app with 30+ guided routines.',
    keyBenefits: ['16mm amplitude (deepest available)', '60 lbs stall force', 'Rotating arm for hard-to-reach areas', 'OLED screen + 30+ app routines', '150 min battery (2 batteries)'],
    bestFor: 'Athletes and serious users wanting maximum depth and guidance',
    affiliateUrl: '/go/theragun-pro-6',
    reviewSlug: 'recovery/best-massage-guns-percussive-therapy',
    reviewLabel: 'Read Full Massage Gun Review',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&q=80',
  },
  {
    id: 'hypervolt-2-pro',
    name: 'Hypervolt 2 Pro',
    brand: 'Hyperice',
    tagline: 'Quietest premium massage gun — 55dB at full speed',
    category: 'Massage & Recovery',
    goals: ['Recovery', 'Inflammation'],
    evidenceLevel: 'Moderate',
    evidenceScore: 78,
    safetyScore: 97,
    popularityScore: 88,
    price: '$329',
    badge: 'Runner-Up',
    summary: 'The quietest high-end massage gun tested at 55dB. Pressure sensor guides optimal force, Bluetooth app integration, excellent ergonomics.',
    keyBenefits: ['Quietest device tested (55dB)', 'Pressure sensor feedback', '5 speeds + 5 attachments', 'Great balance & ergonomics'],
    bestFor: 'Home users who want quiet operation and smart guidance',
    affiliateUrl: '/go/hypervolt-2-pro',
    reviewSlug: 'recovery/best-massage-guns-percussive-therapy',
    reviewLabel: 'Read Full Massage Gun Review',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&q=80',
  },

  // ─── SUPPLEMENTS ──────────────────────────────────────────────────────
  {
    id: 'nmn',
    name: 'NMN Pro',
    brand: 'ProHealth Longevity',
    tagline: 'Best-tested NMN — 500mg sublingual, third-party verified',
    category: 'NAD+ Precursors',
    goals: ['Longevity', 'Energy', 'Cognitive'],
    evidenceLevel: 'Moderate',
    evidenceScore: 72,
    safetyScore: 92,
    popularityScore: 95,
    price: '$67.99',
    badge: 'Best Pick',
    summary: 'ProHealth Longevity NMN Pro is independently third-party tested and offers a sublingual delivery option for improved bioavailability. 500mg pure NMN per serving.',
    keyBenefits: ['Third-party purity tested', '500mg NMN per serving', 'Sublingual option available', 'No fillers or additives'],
    bestFor: 'NAD+ restoration and longevity supplementation',
    affiliateUrl: '/go/prohealth-nmn',
    reviewSlug: 'supplements/best-nmn-supplements-2024',
    reviewLabel: 'Read Full NMN Review',
    dosage: '250–500mg/day',
    timing: 'Morning',
    stacksWith: ['tmg', 'resveratrol', 'coq10'],
    studyCount: 42,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'nr-tru-niagen',
    name: 'Tru Niagen',
    brand: 'ChromaDex',
    tagline: 'Most studied NR — patented formula with 38+ clinical trials',
    category: 'NAD+ Precursors',
    goals: ['Longevity', 'Energy'],
    evidenceLevel: 'Moderate',
    evidenceScore: 69,
    safetyScore: 95,
    popularityScore: 88,
    price: '$47.99',
    badge: 'Runner-Up',
    summary: 'Tru Niagen uses patented nicotinamide riboside (NR) with more published human clinical trials than any other NAD+ precursor. The safe, well-studied choice.',
    keyBenefits: ['Patented Niagen NR formula', '38+ human clinical trials', 'No fishy taste', 'Well-tolerated'],
    bestFor: 'Those who prefer more human trial data over NMN',
    affiliateUrl: '/go/tru-niagen',
    reviewSlug: 'supplements/best-nmn-supplements-2024',
    reviewLabel: 'Read NMN vs NR Review',
    dosage: '300–600mg/day',
    timing: 'Morning',
    studyCount: 38,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'omega3-carlson',
    name: 'Elite Omega-3',
    brand: 'Carlson',
    tagline: 'IFOS 5-star rated — 1600mg EPA+DHA, Friend of the Sea certified',
    category: 'Omega Fatty Acids',
    goals: ['Cardiovascular', 'Inflammation', 'Cognitive', 'Longevity'],
    evidenceLevel: 'Strong',
    evidenceScore: 88,
    safetyScore: 95,
    popularityScore: 92,
    price: '$34.99',
    badge: 'Best Pick',
    summary: 'Carlson Elite Omega-3 is IFOS 5-star certified — the highest purity standard for fish oil. 1600mg EPA+DHA per serving from Friend-of-the-Sea certified sources.',
    keyBenefits: ['IFOS 5-star purity certified', '1600mg EPA+DHA per serving', 'Friend-of-the-Sea certified', 'No fishy aftertaste (lemon flavour)'],
    bestFor: 'Daily cardiovascular and anti-inflammatory omega-3 supplementation',
    affiliateUrl: '/go/carlson-omega3',
    reviewSlug: 'supplements/best-omega-3-fish-oil',
    reviewLabel: 'Read Full Omega-3 Review',
    dosage: '2–4g EPA+DHA daily',
    timing: 'With meals',
    studyCount: 843,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'creatine-mono',
    name: 'Creatine Monohydrate',
    brand: 'Thorne',
    tagline: 'Most evidence-backed supplement in sports science — 5g/day',
    category: 'Mitochondrial Support',
    goals: ['Strength & Muscle', 'Cognitive', 'Energy', 'Longevity'],
    evidenceLevel: 'Strong',
    evidenceScore: 91,
    safetyScore: 98,
    popularityScore: 95,
    price: '$39.99',
    badge: "Editor's Choice",
    summary: "Creatine monohydrate has 500+ studies supporting its efficacy. Thorne's pharmaceutical-grade NSF-certified version is clean, effective, and trusted by professional athletes.",
    keyBenefits: ['500+ supporting studies', 'NSF Certified for Sport', 'No loading phase needed', 'Cognitive + physical benefits', 'Pharmaceutical-grade manufacturing'],
    bestFor: 'Everyone over 30 — the most evidence-backed supplement for longevity beyond the gym',
    affiliateUrl: '/go/thorne-creatine',
    dosage: '3–5g/day',
    timing: 'Anytime — consistency matters',
    studyCount: 500,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'magnesium-glycinate',
    name: 'Magnesium Glycinate',
    brand: 'Pure Encapsulations',
    tagline: 'Best-absorbed magnesium — sleep, recovery, cardiovascular',
    category: 'Vitamins & Minerals',
    goals: ['Sleep', 'Cardiovascular', 'Recovery', 'Cognitive'],
    evidenceLevel: 'Strong',
    evidenceScore: 82,
    safetyScore: 97,
    popularityScore: 93,
    price: '$28.99',
    badge: 'Best Pick',
    summary: 'Magnesium glycinate has the best absorption-to-tolerance ratio of all magnesium forms. Pure Encapsulations is hypoallergenic and free from common fillers.',
    keyBenefits: ['Glycinate form — best absorbed', 'Hypoallergenic formula', 'No GI side effects', 'Supports sleep onset and quality'],
    bestFor: 'Sleep quality, muscle relaxation, and cardiovascular health',
    affiliateUrl: '/go/pure-mag-glycinate',
    dosage: '200–400mg elemental',
    timing: 'Evening, 1 hour before bed',
    studyCount: 289,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'vitamin-d3-k2',
    name: 'Vitamin D3+K2',
    brand: 'Thorne',
    tagline: 'D3 with MK-7 K2 — bone, immune, cardiovascular support',
    category: 'Vitamins & Minerals',
    goals: ['Longevity', 'Cardiovascular', 'Inflammation'],
    evidenceLevel: 'Strong',
    evidenceScore: 84,
    safetyScore: 90,
    popularityScore: 94,
    price: '$24.99',
    badge: 'Best Pick',
    summary: "D3 paired with MK-7 K2 ensures calcium goes to bones not arteries. Thorne's 1000 IU D3 + 200mcg K2 combination is the gold standard for supplementation.",
    keyBenefits: ['D3 + MK-7 K2 combination', 'Ensures proper calcium direction', 'NSF Certified', 'Optimal absorption with fat'],
    bestFor: 'Correcting vitamin D deficiency (>40% of adults) safely',
    affiliateUrl: '/go/thorne-d3k2',
    dosage: '2,000–5,000 IU D3 daily',
    timing: 'Morning with a fatty meal',
    studyCount: 612,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'coq10-ubiquinol',
    name: 'Ubiquinol CoQ10',
    brand: 'Jarrow Formulas',
    tagline: 'Ubiquinol form — superior absorption for mitochondrial energy',
    category: 'Mitochondrial Support',
    goals: ['Energy', 'Cardiovascular', 'Longevity'],
    evidenceLevel: 'Moderate',
    evidenceScore: 74,
    safetyScore: 96,
    popularityScore: 85,
    price: '$42.99',
    badge: 'Best Pick',
    summary: 'Ubiquinol is the active, reduced form of CoQ10 with superior bioavailability — especially important over age 40 when conversion from ubiquinone declines.',
    keyBenefits: ['Ubiquinol form (better absorbed)', 'Essential for statin users', 'Declines with age — supplementation restores', 'Lipid-soluble antioxidant'],
    bestFor: 'People over 40, statin users, and those optimising mitochondrial function',
    affiliateUrl: '/go/jarrow-ubiquinol',
    dosage: '100–300mg/day',
    timing: 'With a fatty meal',
    studyCount: 156,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'ashwagandha-ksm66',
    name: 'KSM-66 Ashwagandha',
    brand: 'Ixoreal / KSM-66',
    tagline: 'Most studied ashwagandha extract — 67 clinical trials',
    category: 'Adaptogens',
    goals: ['Sleep', 'Recovery', 'Cognitive', 'Energy'],
    evidenceLevel: 'Moderate',
    evidenceScore: 71,
    safetyScore: 88,
    popularityScore: 92,
    price: '$22.99',
    badge: 'Best Pick',
    summary: 'KSM-66 is the most clinically studied ashwagandha extract. 67 peer-reviewed studies demonstrate cortisol reduction, sleep improvement, and testosterone support.',
    keyBenefits: ['67 clinical trials (most studied)', 'Reduces cortisol up to 30%', 'Improves sleep onset and quality', 'Testosterone + strength support'],
    bestFor: 'Stress management, sleep improvement, and cortisol reduction',
    affiliateUrl: '/go/ksm66-ashwagandha',
    dosage: '300–600mg KSM-66',
    timing: 'Evening (or split AM/PM)',
    studyCount: 67,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'berberine-hcl',
    name: 'Berberine HCl',
    brand: 'Thorne',
    tagline: "Nature's metformin — AMPK activator with cardiovascular benefits",
    category: 'Mitochondrial Support',
    goals: ['Longevity', 'Cardiovascular', 'Metabolic Health'],
    evidenceLevel: 'Moderate',
    evidenceScore: 76,
    safetyScore: 80,
    popularityScore: 84,
    price: '$35.99',
    badge: 'Best Pick',
    summary: 'Berberine activates AMPK (the same pathway as metformin), improving insulin sensitivity and cardiovascular markers. Multiple RCTs show meaningful glycaemic and lipid benefits.',
    keyBenefits: ['AMPK activator', 'Improves insulin sensitivity', 'Lowers LDL and triglycerides', 'Multiple RCTs in humans'],
    bestFor: 'Metabolic health, blood glucose management, and longevity signalling',
    affiliateUrl: '/go/thorne-berberine',
    dosage: '500mg 2–3x/day with meals',
    timing: 'With meals',
    studyCount: 89,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },

  // ─── ANTIOXIDANTS & SENOLYTICS ────────────────────────────────────────
  {
    id: 'ndga',
    name: 'NDGA (Nordihydroguaiaretic Acid)',
    brand: 'Double Wood',
    tagline: 'One of only a handful of compounds with replicated ITP mouse lifespan extension',
    category: 'Antioxidants & Senolytics',
    goals: ['Longevity', 'Inflammation'],
    evidenceLevel: 'Emerging',
    evidenceScore: 64,
    safetyScore: 80,
    popularityScore: 42,
    price: '$28.99',
    summary: 'Extracted from the creosote bush, NDGA extended median lifespan in male mice in the NIA Interventions Testing Program — the gold-standard, multi-site mouse longevity study. Bryan Johnson added 50mg/day to his Blueprint stack in 2026 on the strength of this animal data. Human evidence is essentially nonexistent.',
    keyBenefits: ['Replicated lifespan extension in ITP mouse studies', 'Potent lipoxygenase inhibitor (anti-inflammatory)', 'Antioxidant via free radical scavenging', 'Added to Bryan Johnson\'s 2026 Blueprint stack'],
    bestFor: 'Experimental longevity stackers comfortable acting on strong animal — but no human — data',
    affiliateUrl: '/go/ndga',
    dosage: '50mg/day (Bryan Johnson\'s dose)',
    timing: 'With food',
    studyCount: 6,
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&q=80',
  },
  {
    id: 'fisetin',
    name: 'Fisetin',
    brand: 'Life Extension',
    tagline: 'Potent senolytic — clears zombie cells, strongest plant senolytic tested',
    category: 'Antioxidants & Senolytics',
    goals: ['Longevity', 'Cognitive', 'Inflammation'],
    evidenceLevel: 'Emerging',
    evidenceScore: 74,
    safetyScore: 92,
    popularityScore: 78,
    price: '$22.99',
    badge: 'Best Pick',
    summary: 'Fisetin is a flavonoid found in strawberries with the strongest senolytic activity of any plant compound tested. David Sinclair uses 500mg daily after dropping quercetin in 2023.',
    keyBenefits: ['Strongest plant senolytic in animal studies', 'Blood-brain barrier penetrant — neuroprotective', "David Sinclair's preferred senolytic", 'Autophagy activation', 'Anti-inflammatory'],
    bestFor: 'Longevity-focused individuals targeting senescent cell clearance',
    affiliateUrl: '/go/fisetin-lifeext',
    dosage: '100–500mg/day or pulsed 1g for 2 days monthly',
    timing: 'With a fatty meal',
    studyCount: 24,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'quercetin',
    name: 'Quercetin',
    brand: 'Thorne',
    tagline: 'Senolytic flavonoid — often stacked with dasatinib for zombie cell clearance',
    category: 'Antioxidants & Senolytics',
    goals: ['Longevity', 'Inflammation', 'Cardiovascular'],
    evidenceLevel: 'Emerging',
    evidenceScore: 62,
    safetyScore: 92,
    popularityScore: 76,
    price: '$28.99',
    summary: "Quercetin was a key part of Sinclair's stack until 2023 (dropped over SIRT6 concern). Still widely used as a senolytic — typically pulsed, not daily.",
    keyBenefits: ['Senolytic activity (pulsed protocol)', 'Anti-inflammatory via NF-κB', 'Cardiovascular protection', 'Quercetin + Dasatinib combo most studied'],
    bestFor: 'Pulsed senolytic protocols (2 days on, 2 weeks off)',
    affiliateUrl: '/go/thorne-quercetin',
    dosage: '500–1000mg pulsed (2 days on, 2 weeks off)',
    timing: 'With food during pulse days',
    stacksWith: ['fisetin'],
    studyCount: 34,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'resveratrol',
    name: 'Trans-Resveratrol',
    brand: 'Thorne',
    tagline: "Sirtuin activator — David Sinclair's signature longevity compound",
    category: 'Antioxidants & Senolytics',
    goals: ['Longevity', 'Cardiovascular', 'Inflammation'],
    evidenceLevel: 'Emerging',
    evidenceScore: 58,
    safetyScore: 88,
    popularityScore: 82,
    price: '$35.99',
    summary: "Resveratrol activates SIRT1 and is central to Sinclair's longevity strategy. Human data is more mixed than animal studies — but mechanistic plausibility and Sinclair's personal use keep it popular.",
    keyBenefits: ['SIRT1 activator', 'Anti-inflammatory via NF-κB', 'Cardiovascular protection', 'Synergistic with NMN'],
    bestFor: 'Sirtuin activation as part of a NAD+ + resveratrol protocol',
    affiliateUrl: '/go/thorne-resveratrol',
    dosage: '500mg–1g/day',
    timing: 'Morning with olive oil or yoghurt (fat required)',
    stacksWith: ['nmn', 'tmg'],
    studyCount: 127,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },

  // ─── ADAPTOGENS (additional) ──────────────────────────────────────────
  {
    id: 'rhodiola-rosea',
    name: 'Rhodiola Rosea',
    brand: 'Gaia Herbs',
    tagline: 'Evidence-backed adaptogen for stress, fatigue, and cognitive performance',
    category: 'Adaptogens',
    goals: ['Energy', 'Cognitive', 'Recovery'],
    evidenceLevel: 'Moderate',
    evidenceScore: 68,
    safetyScore: 90,
    popularityScore: 79,
    price: '$24.99',
    summary: 'Rhodiola rosea reduces mental fatigue and improves cognitive performance under stress. SHR-5 extract has the most clinical data. Bryan Johnson includes Rhodiola in his morning stack.',
    keyBenefits: ['Reduces mental fatigue (multiple RCTs)', 'Improves focus under stress', 'Adaptogenic — bidirectional stress response', 'Bryan Johnson includes in Blueprint'],
    bestFor: 'Mental performance, stress resilience, and fatigue reduction',
    affiliateUrl: '/go/gaia-rhodiola',
    dosage: '200–600mg SHR-5 extract',
    timing: 'Morning (may disrupt sleep if taken late)',
    stacksWith: ['ashwagandha-ksm66', 'l-theanine'],
    studyCount: 36,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'lions-mane',
    name: "Lion's Mane Mushroom",
    brand: 'Host Defense',
    tagline: 'NGF stimulator — the only mushroom with clinical cognitive data',
    category: 'Adaptogens',
    goals: ['Cognitive', 'Longevity', 'Recovery'],
    evidenceLevel: 'Emerging',
    evidenceScore: 65,
    safetyScore: 95,
    popularityScore: 84,
    price: '$29.99',
    summary: "Lion's Mane stimulates Nerve Growth Factor (NGF) synthesis — promoting neuroplasticity, myelination, and cognitive function. 3 human RCTs show significant cognitive improvement in older adults.",
    keyBenefits: ['Stimulates NGF and BDNF', '3 human RCTs in cognitive impairment', 'Promotes myelination', 'Neuroprotective', 'Safe long-term use data'],
    bestFor: 'Cognitive longevity and neuroplasticity support',
    affiliateUrl: '/go/hostdefense-lionsmane',
    dosage: '500–1000mg extract (30% beta-glucans)',
    timing: 'Morning with food',
    studyCount: 18,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },

  // ─── VITAMINS & MINERALS (additional) ────────────────────────────────
  {
    id: 'vitamin-c',
    name: 'Vitamin C (Liposomal)',
    brand: 'LivOn Labs',
    tagline: 'Most bioavailable vitamin C — liposomal delivery for superior absorption',
    category: 'Vitamins & Minerals',
    goals: ['Longevity', 'Inflammation', 'Cardiovascular'],
    evidenceLevel: 'Strong',
    evidenceScore: 80,
    safetyScore: 97,
    popularityScore: 93,
    price: '$39.99',
    summary: 'Liposomal vitamin C achieves plasma levels comparable to IV administration. Strong evidence for collagen synthesis, immune function, and as a cofactor for carnitine and neurotransmitter biosynthesis.',
    keyBenefits: ['Liposomal = 5-10x higher plasma levels', 'Collagen synthesis cofactor', 'Immune modulation', 'Antioxidant regeneration (recycles vitamin E)', 'Endothelial function support'],
    bestFor: 'High-dose vitamin C without GI side effects of standard oral forms',
    affiliateUrl: '/go/livon-vitamin-c',
    dosage: '1–4g/day in divided doses',
    timing: 'Morning and afternoon',
    studyCount: 612,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'zinc-picolinate',
    name: 'Zinc Picolinate',
    brand: 'Thorne',
    tagline: 'Best-absorbed zinc — immune, testosterone, and protein synthesis',
    category: 'Vitamins & Minerals',
    goals: ['Longevity', 'Energy', 'Recovery'],
    evidenceLevel: 'Strong',
    evidenceScore: 79,
    safetyScore: 90,
    popularityScore: 88,
    price: '$18.99',
    badge: 'Best Pick',
    summary: 'Zinc picolinate has the highest absorption rate of all zinc forms. Zinc deficiency (common in athletes and the elderly) directly suppresses testosterone and immune function. Huberman and Attia both include zinc in their stacks.',
    keyBenefits: ['Highest absorption form (picolinate chelate)', 'Testosterone synthesis cofactor', 'Immune function essential', 'DNA synthesis and repair', 'Taste and smell receptor function'],
    bestFor: 'Athletes, elderly, and anyone with high zinc losses through sweat',
    affiliateUrl: '/go/thorne-zinc',
    dosage: '15–30mg elemental zinc',
    timing: 'Evening with food (zinc can cause nausea on empty stomach)',
    studyCount: 245,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'nac',
    name: 'N-Acetyl Cysteine (NAC)',
    brand: 'Jarrow Formulas',
    tagline: 'Glutathione precursor — master antioxidant replenishment',
    category: 'Vitamins & Minerals',
    goals: ['Longevity', 'Inflammation', 'Cognitive'],
    evidenceLevel: 'Moderate',
    evidenceScore: 73,
    safetyScore: 88,
    popularityScore: 80,
    price: '$21.99',
    summary: "NAC is the rate-limiting precursor to glutathione — the body's master antioxidant. Reduces oxidative stress, supports liver detoxification, and has mucolytic properties. Widely used in clinical medicine.",
    keyBenefits: ['Glutathione precursor', 'Liver protection and detoxification', 'Mucolytic (respiratory health)', 'OCD/compulsive behaviour data', 'Reduces oxidative stress markers'],
    bestFor: 'Glutathione restoration, liver support, and oxidative stress reduction',
    affiliateUrl: '/go/jarrow-nac',
    dosage: '600–1800mg/day in divided doses',
    timing: 'Away from meals (better absorption)',
    studyCount: 189,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'tmg',
    name: 'TMG (Trimethylglycine)',
    brand: 'Jarrow Formulas',
    tagline: 'Essential methyl donor when stacking NMN or NR',
    category: 'Vitamins & Minerals',
    goals: ['Longevity', 'Cardiovascular', 'Energy'],
    evidenceLevel: 'Emerging',
    evidenceScore: 60,
    safetyScore: 90,
    popularityScore: 72,
    price: '$19.99',
    summary: 'TMG is a methyl donor that counteracts the methylation depletion caused by NMN and NR supplementation. Lowers homocysteine and is increasingly recommended as a stack partner for NAD+ precursors.',
    keyBenefits: ['Counteracts NMN-induced methylation depletion', 'Lowers homocysteine', 'Osmolyte — cell volume regulation', 'Liver protection', 'Athletic performance (betaine)'],
    bestFor: 'Anyone taking NMN or NR — methylation support is essential',
    affiliateUrl: '/go/jarrow-tmg',
    dosage: '500mg–3g/day',
    timing: 'Morning with NMN/NR',
    stacksWith: ['nmn', 'nr-tru-niagen'],
    studyCount: 28,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },

  // ─── MITOCHONDRIAL SUPPORT (additional) ──────────────────────────────
  {
    id: 'pqq',
    name: 'PQQ (Pyrroloquinoline Quinone)',
    brand: 'Jarrow Formulas',
    tagline: 'Mitochondrial biogenesis — the only compound that grows new mitochondria',
    category: 'Mitochondrial Support',
    goals: ['Energy', 'Cognitive', 'Longevity'],
    evidenceLevel: 'Emerging',
    evidenceScore: 64,
    safetyScore: 90,
    popularityScore: 70,
    price: '$26.99',
    summary: 'PQQ is unique in that it stimulates mitochondrial biogenesis — the growth of new mitochondria. Most supplements support existing mitochondria; PQQ may actually increase their number.',
    keyBenefits: ['Stimulates mitochondrial biogenesis (PGC-1alpha)', 'Neuroprotective', 'Improves energy and cognitive function', 'Synergistic with CoQ10'],
    bestFor: 'Mitochondrial biogenesis stacked with CoQ10',
    affiliateUrl: '/go/jarrow-pqq',
    dosage: '10–20mg/day',
    timing: 'Morning with food',
    stacksWith: ['coq10-ubiquinol'],
    studyCount: 22,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'alpha-lipoic-acid',
    name: 'R-Alpha Lipoic Acid',
    brand: 'Jarrow Formulas',
    tagline: 'Universal antioxidant — regenerates vitamin C, E and glutathione',
    category: 'Mitochondrial Support',
    goals: ['Longevity', 'Energy', 'Metabolic Health'],
    evidenceLevel: 'Moderate',
    evidenceScore: 66,
    safetyScore: 88,
    popularityScore: 74,
    price: '$24.99',
    summary: "R-ALA is the biologically active form of alpha-lipoic acid. It regenerates other antioxidants (vitamin C, E, glutathione), improves insulin sensitivity, and is part of David Sinclair's daily stack.",
    keyBenefits: ['Regenerates vitamin C, E, CoQ10 and glutathione', 'Improves insulin sensitivity', 'Crosses blood-brain barrier', 'Chelates heavy metals', "David Sinclair's stack"],
    bestFor: 'Antioxidant network support and glucose metabolism',
    affiliateUrl: '/go/jarrow-rala',
    dosage: '100–300mg R-ALA (not racemic)',
    timing: 'With meals',
    stacksWith: ['coq10-ubiquinol', 'nac'],
    studyCount: 78,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'taurine',
    name: 'Taurine',
    brand: 'NOW Foods',
    tagline: 'Taurine deficiency linked to aging — may be the longevity molecule of 2023',
    category: 'Mitochondrial Support',
    goals: ['Longevity', 'Cardiovascular', 'Energy'],
    evidenceLevel: 'Emerging',
    evidenceScore: 67,
    safetyScore: 96,
    popularityScore: 76,
    price: '$14.99',
    badge: 'Best Pick',
    summary: 'A 2023 Science paper showed taurine deficiency drives aging across multiple species, and supplementation extended lifespan in mice by 10-12%. One of the most discussed longevity papers of the decade.',
    keyBenefits: ['2023 Science paper: taurine deficiency drives aging', 'Lifespan extension in multiple animal models', 'Cardiovascular protection', 'Mitochondrial function', 'Very safe — high natural occurrence'],
    bestFor: 'Longevity optimisation based on emerging taurine-aging research',
    affiliateUrl: '/go/now-taurine',
    dosage: '1–3g/day',
    timing: 'Morning or pre-workout',
    studyCount: 45,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'spermidine',
    name: 'Spermidine',
    brand: 'Primeadine',
    tagline: 'Autophagy inducer from wheat germ — cellular self-cleaning activation',
    category: 'Mitochondrial Support',
    goals: ['Longevity', 'Cognitive', 'Cardiovascular'],
    evidenceLevel: 'Emerging',
    evidenceScore: 62,
    safetyScore: 93,
    popularityScore: 68,
    price: '$59.99',
    summary: "Spermidine induces autophagy — the cellular self-cleaning process that declines with age. David Sinclair and multiple longevity researchers now include it. Human RCTs show cognitive protection and cardiovascular benefits.",
    keyBenefits: ['Potent autophagy inducer', 'Cognitive protection in human RCTs', 'Cardiovascular data emerging', "David Sinclair's stack", 'Natural — found in aged cheese and wheat germ'],
    bestFor: 'Autophagy activation and longevity — especially combined with intermittent fasting',
    affiliateUrl: '/go/primeadine-spermidine',
    dosage: '1–2mg/day',
    timing: 'Morning away from food',
    studyCount: 31,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },

  // ─── OMEGA FATTY ACIDS (additional) ──────────────────────────────────
  {
    id: 'nordic-naturals-omega3',
    name: 'Ultimate Omega',
    brand: 'Nordic Naturals',
    tagline: 'Triglyceride form omega-3 — best absorbed, no fishy taste',
    category: 'Omega Fatty Acids',
    goals: ['Cardiovascular', 'Inflammation', 'Cognitive'],
    evidenceLevel: 'Strong',
    evidenceScore: 86,
    safetyScore: 95,
    popularityScore: 90,
    price: '$52.99',
    badge: 'Runner-Up',
    summary: 'Nordic Naturals Ultimate Omega uses the triglyceride form of omega-3 — the natural form found in fish, with superior absorption vs ethyl ester form. No fishy aftertaste.',
    keyBenefits: ['Triglyceride form = best absorption', 'No fishy aftertaste', 'Third-party tested', '1280mg EPA+DHA per serving', 'Friend of the Sea certified'],
    bestFor: 'Those who want the best-absorbed form of omega-3 and cannot tolerate fishy taste',
    affiliateUrl: '/go/nordic-omega3',
    dosage: '2–4g EPA+DHA daily',
    timing: 'With meals',
    studyCount: 843,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },

  // ─── NAD+ PRECURSORS (additional) ────────────────────────────────────
  {
    id: 'ca-akg',
    name: 'Ca-AKG (Calcium Alpha-Ketoglutarate)',
    brand: 'Life Extension',
    tagline: 'TCA cycle intermediate — extended biological age reversal data',
    category: 'NAD+ Precursors',
    goals: ['Longevity', 'Energy'],
    evidenceLevel: 'Emerging',
    evidenceScore: 61,
    safetyScore: 88,
    popularityScore: 65,
    price: '$29.99',
    summary: "Ca-AKG is a TCA cycle intermediate that declined with age. A 2021 Cell Metabolism paper showed it extended healthspan in mice by 18% and reversed biological age markers. Included in Bryan Johnson's Blueprint stack.",
    keyBenefits: ['2021 Cell Metabolism study: 18% healthspan extension in mice', 'TCA cycle substrate', "Bryan Johnson's Blueprint includes it", 'Biological age marker improvement', 'Epigenetic clock reversal in human pilot data'],
    bestFor: 'Advanced longevity stack — for those wanting to target the TCA cycle',
    affiliateUrl: '/go/lifeext-caakg',
    dosage: '1–2g/day',
    timing: 'Morning',
    studyCount: 12,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },

  // ─── BLOOD DIAGNOSTICS ────────────────────────────────────────────────
  {
    id: 'function-health',
    name: 'Function Health',
    brand: 'Function',
    tagline: '160+ biomarkers — the most comprehensive DTC blood panel',
    category: 'Blood & Diagnostics',
    goals: ['Longevity', 'Cardiovascular', 'Metabolic Health'],
    evidenceLevel: 'Strong',
    evidenceScore: 94,
    safetyScore: 99,
    popularityScore: 88,
    price: '$499/year',
    badge: 'Best Pick',
    summary: 'Function Health offers 160+ biomarkers including ApoB, Lp(a), fasting insulin, homocysteine, and TMAO — more than most concierge practices. Co-founded by Dr. Mark Hyman.',
    keyBenefits: ['160+ biomarkers', 'Includes ApoB, Lp(a), fasting insulin', 'Physician-reviewed results', 'Year-over-year trending', '2 panels per year included'],
    bestFor: 'Comprehensive annual health baseline and longevity tracking',
    affiliateUrl: '/go/function-health',
    reviewSlug: 'diagnostics/best-at-home-blood-tests-2024',
    reviewLabel: 'Read Full Blood Test Review',
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&q=80',
  },
  {
    id: 'insidetracker',
    name: 'InsideTracker Ultimate',
    brand: 'InsideTracker',
    tagline: 'Athlete-optimised blood + DNA testing with food recommendations',
    category: 'Blood & Diagnostics',
    goals: ['Longevity', 'Cardiovascular', 'Strength & Muscle'],
    evidenceLevel: 'Strong',
    evidenceScore: 86,
    safetyScore: 99,
    popularityScore: 84,
    price: '$299–699',
    badge: 'Runner-Up',
    summary: 'InsideTracker optimises for athletic performance and longevity. Strong mobile app with personalised food and supplement recommendations based on your bloodwork and DNA.',
    keyBenefits: ['Athlete-optimised biomarkers', 'DNA + blood combination available', 'Personalised food recommendations', 'Optimal zones not just normal ranges'],
    bestFor: 'Athletes wanting bloodwork integrated with performance optimisation',
    affiliateUrl: '/go/insidetracker',
    reviewSlug: 'diagnostics/best-at-home-blood-tests-2024',
    reviewLabel: 'Read Full Blood Test Review',
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&q=80',
  },

  // ─── SLEEP AIDS ─────────────────────────────────────────────────────────
  {
    id: 'melatonin-timed-release',
    name: 'Melatonin (Timed-Release)',
    brand: 'Life Extension',
    tagline: 'Slow-release dosing matched to natural overnight melatonin curve',
    category: 'Sleep Aids',
    goals: ['Sleep', 'Longevity'],
    evidenceLevel: 'Strong',
    evidenceScore: 82,
    safetyScore: 93,
    popularityScore: 86,
    price: '$10.99',
    badge: 'Best Pick',
    summary: 'Timed-release melatonin avoids the next-morning grogginess of standard formulations by mimicking the body\'s natural overnight melatonin release curve. Strong evidence for reducing sleep-onset latency and improving circadian alignment.',
    keyBenefits: ['Reduces sleep onset latency', 'Mimics natural melatonin curve', 'Low next-day grogginess', 'Useful for jet lag and shift work'],
    bestFor: 'Circadian rhythm support and falling asleep faster',
    affiliateUrl: '/go/melatonin-timed-release',
    dosage: '0.5–3mg, 30–60 min before bed',
    timing: 'Evening, 30–60 minutes before sleep',
    studyCount: 24,
    image: 'https://images.unsplash.com/photo-1600618528240-fb9fc964b853?w=400&q=80',
  },
  {
    id: 'blue-light-blocking-glasses',
    name: 'Blue-Light Blocking Glasses',
    brand: 'BLUblox',
    tagline: 'Amber-lens glasses for evening circadian protection',
    category: 'Sleep Aids',
    goals: ['Sleep'],
    evidenceLevel: 'Moderate',
    evidenceScore: 71,
    safetyScore: 99,
    popularityScore: 75,
    price: '$89',
    summary: 'Blocks blue-wavelength light in the evening to prevent suppression of natural melatonin release from screens and indoor lighting. RCTs show modest improvements in sleep quality and onset when worn consistently 2+ hours before bed.',
    keyBenefits: ['Blocks 99%+ blue light', 'No supplements or chemicals', 'Pairs well with melatonin protocols', 'One-time purchase'],
    bestFor: 'Screen-heavy evenings and delayed sleep phase',
    affiliateUrl: '/go/blublox-glasses',
    timing: 'Worn 2+ hours before bed',
    studyCount: 9,
    image: 'https://images.unsplash.com/photo-1633621412960-6df85eff8c85?w=400&q=80',
  },

  // ─── NOOTROPICS & COGNITIVE ──────────────────────────────────────────────
  {
    id: 'citicoline-cognizin',
    name: 'Citicoline (Cognizin)',
    brand: 'Double Wood',
    tagline: 'Clinically dosed choline source for focus and memory',
    category: 'Nootropics & Cognitive',
    goals: ['Cognitive', 'Longevity'],
    evidenceLevel: 'Strong',
    evidenceScore: 84,
    safetyScore: 96,
    popularityScore: 78,
    price: '$24.99',
    badge: 'Best Pick',
    summary: 'Citicoline increases acetylcholine and phosphatidylcholine synthesis, supporting attention, working memory, and brain energy metabolism. The patented Cognizin form has the strongest clinical backing of any choline source.',
    keyBenefits: ['Boosts acetylcholine synthesis', 'Multiple RCTs in attention/memory', 'Supports brain phospholipid membranes', 'Well-tolerated long-term'],
    bestFor: 'Focus, working memory, and brain energy metabolism',
    affiliateUrl: '/go/citicoline-cognizin',
    dosage: '250–500mg daily',
    timing: 'Morning, with or without food',
    studyCount: 15,
    image: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400&q=80',
  },
  {
    id: 'bacopa-monnieri',
    name: 'Bacopa Monnieri',
    brand: 'Himalaya',
    tagline: 'Ayurvedic herb with the deepest memory-formation evidence base',
    category: 'Nootropics & Cognitive',
    goals: ['Cognitive', 'Longevity'],
    evidenceLevel: 'Strong',
    evidenceScore: 80,
    safetyScore: 92,
    popularityScore: 70,
    price: '$19.99',
    summary: 'Bacopa Monnieri has the largest body of RCT evidence of any nootropic herb, consistently showing improved memory acquisition and retention after 8-12 weeks of consistent use. Effects build gradually rather than acutely.',
    keyBenefits: ['Largest RCT base of any nootropic herb', 'Improves memory consolidation', 'Antioxidant and adaptogenic effects', 'Well-studied safety profile'],
    bestFor: 'Long-term memory support — requires 8-12 weeks for full effect',
    affiliateUrl: '/go/bacopa-monnieri',
    dosage: '300mg standardized extract (50% bacosides)',
    timing: 'With food, consistent daily use',
    studyCount: 12,
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&q=80',
  },

  {
    id: 'lithium-orotate',
    name: 'Lithium Orotate (Microdose)',
    brand: 'Seeking Health',
    tagline: 'Trace-mineral neuroprotection at a fraction of the bipolar treatment dose',
    category: 'Nootropics & Cognitive',
    goals: ['Cognitive', 'Longevity'],
    evidenceLevel: 'Emerging',
    evidenceScore: 58,
    safetyScore: 73,
    popularityScore: 48,
    price: '$15.99',
    summary: 'Population studies of municipal water supplies consistently associate higher trace lithium levels with lower rates of dementia and all-cause mortality. Microdose lithium orotate (often under 5mg elemental lithium) is far below the therapeutic dose used for bipolar disorder. Bryan Johnson added it to his Blueprint Essential Capsules in 2026. Evidence is epidemiological, not RCT-based — and lithium has a narrow safety margin even at low doses.',
    keyBenefits: ['Epidemiological link to lower dementia rates', 'Sub-clinical dose, far below psychiatric range', 'Added to Bryan Johnson\'s 2026 Blueprint stack', 'May support GSK-3 inhibition relevant to neuroprotection'],
    bestFor: 'Experimental neuroprotection stacking — requires physician oversight and periodic bloodwork',
    affiliateUrl: '/go/lithium-orotate',
    dosage: 'Microdose only — consult a physician; do not self-dose without guidance',
    timing: 'Daily, with food',
    studyCount: 11,
    image: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400&q=80',
  },

  // ─── GUT & MICROBIOME ────────────────────────────────────────────────────
  {
    id: 'seed-ds01',
    name: 'Seed DS-01 Daily Synbiotic',
    brand: 'Seed',
    tagline: '24-strain probiotic with prebiotic capsule-in-capsule delivery',
    category: 'Gut & Microbiome',
    goals: ['Longevity', 'Inflammation', 'Metabolic Health'],
    evidenceLevel: 'Strong',
    evidenceScore: 83,
    safetyScore: 97,
    popularityScore: 82,
    price: '$49.99/month',
    badge: "Editor's Choice",
    summary: 'Seed\'s 24-strain formulation is backed by a published clinical trial and uses a capsule-in-capsule design to survive stomach acid. Gut microbiome diversity is increasingly linked to inflammation, metabolic health, and healthy aging.',
    keyBenefits: ['24 clinically studied strains', 'Published RCT on gut barrier integrity', 'Survives stomach acid via 2-capsule design', 'Includes prebiotic for strain support'],
    bestFor: 'Gut barrier integrity and microbiome diversity',
    affiliateUrl: '/go/seed-ds01',
    dosage: '2 capsules daily',
    timing: 'Empty stomach, before bed or first thing in morning',
    studyCount: 7,
    image: 'https://images.unsplash.com/photo-1543362906-acfc16c67564?w=400&q=80',
  },
]

// ─── Helper functions ──────────────────────────────────────────────────────
export function getProductById(id: string): Product | null {
  return products.find(p => p.id === id) ?? null
}

export function getProductsByCategory(cat: ProductCategory): Product[] {
  return products.filter(p => p.category === cat)
}

export function getProductsByGoal(goal: Goal): Product[] {
  return products.filter(p => p.goals.includes(goal))
}

export const allCategories: ProductCategory[] = [
  'Red Light Therapy',
  'Infrared Saunas',
  'Cold Plunge & Ice Baths',
  'Fitness Trackers & HRV',
  'Continuous Glucose Monitors',
  'Massage & Recovery',
  'NAD+ Precursors',
  'Antioxidants & Senolytics',
  'Adaptogens',
  'Omega Fatty Acids',
  'Vitamins & Minerals',
  'Mitochondrial Support',
  'Blood & Diagnostics',
  'Sleep Aids',
  'Nootropics & Cognitive',
  'Gut & Microbiome',
]

export const categoryGroups: { label: string; categories: ProductCategory[] }[] = [
  { label: 'Recovery Devices', categories: ['Red Light Therapy', 'Infrared Saunas', 'Cold Plunge & Ice Baths', 'Massage & Recovery'] },
  { label: 'Wearables & Tracking', categories: ['Fitness Trackers & HRV', 'Continuous Glucose Monitors', 'Blood & Diagnostics'] },
  { label: 'Supplements', categories: ['NAD+ Precursors', 'Antioxidants & Senolytics', 'Adaptogens', 'Omega Fatty Acids', 'Vitamins & Minerals', 'Mitochondrial Support'] },
  { label: 'Sleep & Cognitive', categories: ['Sleep Aids', 'Nootropics & Cognitive'] },
  { label: 'Gut Health', categories: ['Gut & Microbiome'] },
]

export const evidenceBadgeColors: Record<EvidenceLevel, string> = {
  Strong: 'bg-green/10 text-green-bright border-green/25',
  Moderate: 'bg-amber/10 text-amber border-amber/25',
  Emerging: 'bg-blue-500/10 text-blue-500 border-blue-500/25',
  Weak: 'bg-red-500/10 text-red-400 border-red-500/25',
}

export const badgeColors: Record<string, string> = {
  'Best Pick': 'bg-green/10 text-green-bright border-green/25',
  'Runner-Up': 'bg-amber/10 text-amber border-amber/25',
  'Budget': 'bg-blue-500/10 text-blue-500 border-blue-500/20',
  "Editor's Choice": 'bg-purple-500/10 text-purple-400 border-purple-500/20',
  'Premium': 'bg-amber/10 text-amber border-amber/20',
}
