export type EvidenceLevel = 'Strong' | 'Moderate' | 'Emerging' | 'Weak'
export type ProductCategory =
  | 'Red Light Therapy'
  | 'Infrared Saunas'
  | 'Cold Plunge & Ice Baths'
  | 'Fitness Trackers & HRV'
  | 'Continuous Glucose Monitors'
  | 'Massage & Recovery'
  | 'NAD+ Precursors'
  | 'Antioxidants & Senolytics'
  | 'Adaptogens'
  | 'Omega Fatty Acids'
  | 'Vitamins & Minerals'
  | 'Mitochondrial Support'
  | 'Blood & Diagnostics'

export type Goal =
  | 'Longevity'
  | 'Energy'
  | 'Sleep'
  | 'Cognitive'
  | 'Cardiovascular'
  | 'Recovery'
  | 'Inflammation'
  | 'Metabolic Health'
  | 'Strength & Muscle'
  | 'Skin & Collagen'

export interface Product {
  id: string
  name: string
  brand: string
  tagline: string
  category: ProductCategory
  goals: Goal[]
  evidenceLevel: EvidenceLevel
  evidenceScore: number
  safetyScore: number
  popularityScore: number
  price: string
  summary: string
  keyBenefits: string[]
  bestFor: string
  affiliateUrl?: string
  reviewSlug?: string   // e.g. 'recovery/best-red-light-therapy-panels-2024'
  reviewLabel?: string  // e.g. 'Read Full Review'
  image?: string
  badge?: 'Best Pick' | 'Runner-Up' | 'Budget' | "Editor's Choice" | 'Premium'
  studyCount?: number
  dosage?: string
  timing?: string
  stacksWith?: string[]
}

export const products: Product[] = [

  // ─── RED LIGHT THERAPY ────────────────────────────────────────────────
  {
    id: 'mito-red-1500',
    name: 'MitoPRO 1500',
    brand: 'Mito Red Light',
    tagline: 'Highest irradiance full-body panel in its class',
    category: 'Red Light Therapy',
    goals: ['Recovery', 'Skin & Collagen', 'Energy', 'Inflammation'],
    evidenceLevel: 'Strong',
    evidenceScore: 88,
    safetyScore: 97,
    popularityScore: 90,
    price: '$599',
    badge: 'Best Pick',
    summary: 'The MitoPRO 1500 delivers 97 mW/cm² irradiance — the highest tested in its price range. True dual-chip 660nm + 850nm wavelengths, zero flicker, 5-year warranty.',
    keyBenefits: ['95+ mW/cm² irradiance', 'True 660nm + 850nm dual-chip', 'No EMF at treatment distance', 'Zero flicker confirmed', '5-year warranty'],
    bestFor: 'Full-body red light therapy sessions at home',
    affiliateUrl: '/go/mito-red-1500',
    reviewSlug: 'recovery/best-red-light-therapy-panels-2024',
    reviewLabel: 'Read Full Panel Review',
    image: 'https://images.unsplash.com/photo-1616279969856-759f316a5ac1?w=400&q=80',
    studyCount: 6000,
  },
  {
    id: 'joovv-solo-3',
    name: 'Solo 3.0',
    brand: 'Joovv',
    tagline: 'Premium modular red light system with app control',
    category: 'Red Light Therapy',
    goals: ['Recovery', 'Skin & Collagen', 'Inflammation'],
    evidenceLevel: 'Strong',
    evidenceScore: 82,
    safetyScore: 97,
    popularityScore: 94,
    price: '$1,199',
    badge: 'Runner-Up',
    summary: 'The original consumer red light brand. Beautiful build, app control, ambient mode, and modular design. Irradiance trails cheaper competitors but the ecosystem is unmatched.',
    keyBenefits: ['App-controlled dosing', 'Modular — connects to other panels', 'Ambient mode for circadian support', 'Premium build quality'],
    bestFor: 'Premium buyers who want the full Joovv ecosystem',
    affiliateUrl: '/go/joovv-solo-3',
    reviewSlug: 'recovery/best-red-light-therapy-panels-2024',
    reviewLabel: 'Read Full Panel Review',
    image: 'https://images.unsplash.com/photo-1616279969856-759f316a5ac1?w=400&q=80',
  },
  {
    id: 'biomax-300',
    name: 'BioMax 300',
    brand: 'PlatinumLED',
    tagline: 'Best small panel — 5 wavelengths, ideal for face & joints',
    category: 'Red Light Therapy',
    goals: ['Skin & Collagen', 'Recovery', 'Inflammation'],
    evidenceLevel: 'Strong',
    evidenceScore: 78,
    safetyScore: 97,
    popularityScore: 82,
    price: '$269',
    badge: 'Budget',
    summary: '5-wavelength panel (630, 660, 810, 830, 850nm) in a compact form factor. Best value for targeted face, joint, or injury treatment.',
    keyBenefits: ['5 therapeutic wavelengths', 'Compact — ideal for face & joints', 'Excellent irradiance for size', 'No prescription required'],
    bestFor: 'Targeted treatment and beginners entering red light therapy',
    affiliateUrl: '/go/biomax-300',
    reviewSlug: 'recovery/best-red-light-therapy-panels-2024',
    reviewLabel: 'Read Full Panel Review',
    image: 'https://images.unsplash.com/photo-1616279969856-759f316a5ac1?w=400&q=80',
  },
  {
    id: 'lumebox',
    name: 'LumeBox',
    brand: 'LumeBox',
    tagline: 'Portable travel red light therapy device',
    category: 'Red Light Therapy',
    goals: ['Skin & Collagen', 'Recovery'],
    evidenceLevel: 'Moderate',
    evidenceScore: 70,
    safetyScore: 96,
    popularityScore: 75,
    price: '$349',
    summary: 'Compact, travel-friendly red light device with 660nm + 850nm. Lower total irradiance than full panels but excellent portability.',
    keyBenefits: ['Travel-sized', 'Rechargeable battery', '660nm + 850nm', 'Lightweight (0.8 lbs)'],
    bestFor: 'Travellers wanting red light on the go',
    affiliateUrl: '/go/lumebox',
    image: 'https://images.unsplash.com/photo-1616279969856-759f316a5ac1?w=400&q=80',
  },

  // ─── INFRARED SAUNAS ──────────────────────────────────────────────────
  {
    id: 'sunlighten-mpulse',
    name: 'mPulse Believe',
    brand: 'Sunlighten',
    tagline: 'Full-spectrum infrared sauna with programmable health protocols',
    category: 'Infrared Saunas',
    goals: ['Cardiovascular', 'Recovery', 'Longevity', 'Inflammation'],
    evidenceLevel: 'Strong',
    evidenceScore: 92,
    safetyScore: 95,
    popularityScore: 88,
    price: '$7,995',
    badge: 'Premium',
    summary: 'The most advanced home infrared sauna. Full-spectrum (near, mid, far IR), SoloCarbon heaters at 95% emissivity, programmable health protocols, and built-in tablet.',
    keyBenefits: ['Full-spectrum: near + mid + far IR', 'Programmable longevity protocols', 'Medical-grade SoloCarbon heaters', 'Best-in-class EMF for the spectrum', 'Built-in tablet & chromotherapy'],
    bestFor: 'Serious longevity optimisers wanting the best full-spectrum sauna',
    affiliateUrl: '/go/sunlighten-mpulse',
    reviewSlug: 'recovery/best-home-saunas-infrared-2024',
    reviewLabel: 'Read Full Sauna Review',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&q=80',
  },
  {
    id: 'clearlight-sanctuary',
    name: 'Sanctuary 2',
    brand: 'Clearlight',
    tagline: 'Ultra-low EMF far-infrared sauna with lifetime heater warranty',
    category: 'Infrared Saunas',
    goals: ['Cardiovascular', 'Recovery', 'Longevity'],
    evidenceLevel: 'Strong',
    evidenceScore: 86,
    safetyScore: 97,
    popularityScore: 84,
    price: '$4,999',
    badge: 'Runner-Up',
    summary: 'The lowest-EMF cabin sauna tested. True Wave II carbon/ceramic heaters, Western red cedar construction, 2-person capacity, lifetime warranty on heaters.',
    keyBenefits: ['Ultra-low EMF & ELF', 'True Wave II heaters', 'Western red cedar', 'Lifetime heater warranty', '2-person capacity'],
    bestFor: 'EMF-sensitive buyers wanting premium far-infrared',
    affiliateUrl: '/go/clearlight-sanctuary',
    reviewSlug: 'recovery/best-home-saunas-infrared-2024',
    reviewLabel: 'Read Full Sauna Review',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&q=80',
  },
  {
    id: 'serenelife-sauna',
    name: 'Portable Infrared Sauna',
    brand: 'SereneLife',
    tagline: 'Affordable portable sauna tent — real benefits, no installation',
    category: 'Infrared Saunas',
    goals: ['Recovery', 'Inflammation'],
    evidenceLevel: 'Moderate',
    evidenceScore: 68,
    safetyScore: 90,
    popularityScore: 85,
    price: '$299',
    badge: 'Budget',
    summary: 'Foldable portable sauna tent reaching 140°F. Entry-level heat therapy without installation. Head-out design limits full-body protocol but real sweating and cardiovascular response occurs.',
    keyBenefits: ['No installation required', 'Sets up in minutes', 'Portable & foldable', 'Reaches 140°F'],
    bestFor: 'Renters or beginners testing infrared sauna benefits',
    affiliateUrl: '/go/serenelife-sauna',
    reviewSlug: 'recovery/best-home-saunas-infrared-2024',
    reviewLabel: 'Read Full Sauna Review',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&q=80',
  },

  // ─── COLD PLUNGE ──────────────────────────────────────────────────────
  {
    id: 'the-plunge-pro',
    name: 'The Plunge Pro',
    brand: 'The Plunge',
    tagline: 'Best all-around cold plunge — chills to 37°F with filtration',
    category: 'Cold Plunge & Ice Baths',
    goals: ['Recovery', 'Energy', 'Cardiovascular', 'Inflammation'],
    evidenceLevel: 'Strong',
    evidenceScore: 88,
    safetyScore: 94,
    popularityScore: 91,
    price: '$4,990',
    badge: 'Best Pick',
    summary: 'Sets the standard for home cold plunge units. Chills to 37°F, built-in filtration keeps water clean for weeks, app-controlled scheduling, insulated body.',
    keyBenefits: ['Chills to 37°F (3°C)', 'Built-in filtration + sanitation', 'App scheduling — pre-chill overnight', 'Insulated to maintain temp', '450 lbs capacity'],
    bestFor: 'Serious cold therapy practitioners wanting a set-and-forget system',
    affiliateUrl: '/go/the-plunge-pro',
    reviewSlug: 'recovery/cold-plunge-ice-bath-review',
    reviewLabel: 'Read Full Cold Plunge Review',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80',
  },
  {
    id: 'morozko-forge',
    name: 'Morozko Forge',
    brand: 'Morozko',
    tagline: 'Coldest plunge on the market — chills to 33°F with ozone filtration',
    category: 'Cold Plunge & Ice Baths',
    goals: ['Recovery', 'Energy', 'Cardiovascular'],
    evidenceLevel: 'Strong',
    evidenceScore: 84,
    safetyScore: 93,
    popularityScore: 78,
    price: '$7,990',
    badge: 'Premium',
    summary: 'The coldest consumer cold plunge available — reaches 33°F with ozone-filtered crystal-clear water. Commercial-grade compressor. Overkill for most, perfect for extreme cold therapy enthusiasts.',
    keyBenefits: ['Coldest on market (33°F)', 'Ozone filtration — crystal clear', 'Commercial-grade compressor', 'Can form actual ice'],
    bestFor: 'Cold therapy enthusiasts wanting maximum cold stimulus',
    affiliateUrl: '/go/morozko-forge',
    reviewSlug: 'recovery/cold-plunge-ice-bath-review',
    reviewLabel: 'Read Full Cold Plunge Review',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80',
  },

  // ─── FITNESS TRACKERS ─────────────────────────────────────────────────
  {
    id: 'whoop-4',
    name: 'WHOOP 4.0',
    brand: 'WHOOP',
    tagline: 'Best-in-class HRV tracking and recovery scoring',
    category: 'Fitness Trackers & HRV',
    goals: ['Recovery', 'Sleep', 'Cardiovascular', 'Longevity'],
    evidenceLevel: 'Strong',
    evidenceScore: 91,
    safetyScore: 99,
    popularityScore: 93,
    price: '$239 + $30/mo',
    badge: 'Best Pick',
    summary: 'The gold standard for recovery and HRV tracking. No screen — every resource goes into sensor accuracy. Daily recovery and strain scores, best-in-class sleep staging.',
    keyBenefits: ['Best HRV accuracy (±4.2ms vs ECG)', 'Daily recovery + strain scores', 'Best sleep staging of any wrist device', 'Skin temp + blood oxygen', '24/7 continuous monitoring'],
    bestFor: 'Serious longevity optimisers focused on recovery and HRV',
    affiliateUrl: '/go/whoop-4',
    reviewSlug: 'wearables/best-fitness-trackers-longevity',
    reviewLabel: 'Read Full Tracker Review',
    image: 'https://images.unsplash.com/photo-1510017098667-27dfc7150acb?w=400&q=80',
  },
  {
    id: 'oura-gen3',
    name: 'Ring Gen 3',
    brand: 'Oura',
    tagline: 'Most accurate sleep tracker — worn as a ring',
    category: 'Fitness Trackers & HRV',
    goals: ['Sleep', 'Recovery', 'Cardiovascular', 'Longevity'],
    evidenceLevel: 'Strong',
    evidenceScore: 89,
    safetyScore: 99,
    popularityScore: 91,
    price: '$299 + $5.99/mo',
    badge: "Editor's Choice",
    summary: 'The most accurate consumer sleep tracker available. Finger-based PPG sensors outperform wrist trackers for sleep staging. Continuous skin temperature detects illness 1–3 days early.',
    keyBenefits: ['Best sleep staging accuracy (74% vs PSG)', '7-day battery life', 'Continuous skin temperature', 'Readiness score', 'Discreet ring form factor'],
    bestFor: 'Sleep quality and recovery tracking without wearing a watch',
    affiliateUrl: '/go/oura-gen3',
    reviewSlug: 'wearables/oura-ring-gen3-review',
    reviewLabel: 'Read Full Oura Review',
    image: 'https://images.unsplash.com/photo-1510017098667-27dfc7150acb?w=400&q=80',
  },
  {
    id: 'garmin-fenix7',
    name: 'Fenix 7',
    brand: 'Garmin',
    tagline: 'Best GPS sports watch with HRV and Body Battery',
    category: 'Fitness Trackers & HRV',
    goals: ['Cardiovascular', 'Recovery', 'Longevity'],
    evidenceLevel: 'Strong',
    evidenceScore: 86,
    safetyScore: 99,
    popularityScore: 89,
    price: '$649',
    badge: 'Runner-Up',
    summary: 'Premium GPS watch with serious health tracking — HRV Status, Body Battery recovery score, VO2 max estimation, and 14-day battery. No subscription required.',
    keyBenefits: ['HRV Status (4-week baseline)', 'Body Battery recovery system', 'GPS + multi-sport tracking', '14-day battery life', 'No subscription'],
    bestFor: 'Athletes wanting GPS + longevity health tracking in one device',
    affiliateUrl: '/go/garmin-fenix7',
    reviewSlug: 'wearables/best-fitness-trackers-longevity',
    reviewLabel: 'Read Full Tracker Review',
    image: 'https://images.unsplash.com/photo-1510017098667-27dfc7150acb?w=400&q=80',
  },

  // ─── CGM ──────────────────────────────────────────────────────────────
  {
    id: 'dexcom-stelo',
    name: 'Stelo',
    brand: 'Dexcom',
    tagline: 'First FDA-cleared CGM for non-diabetics — no prescription needed',
    category: 'Continuous Glucose Monitors',
    goals: ['Metabolic Health', 'Longevity', 'Energy'],
    evidenceLevel: 'Strong',
    evidenceScore: 88,
    safetyScore: 98,
    popularityScore: 86,
    price: '$99/month',
    badge: 'Best Pick',
    summary: 'The Dexcom Stelo is the first CGM cleared by the FDA specifically for non-diabetics. No prescription, 14-day wear, MARD of 7.8%, and the best app for metabolic pattern recognition.',
    keyBenefits: ['No prescription required', 'FDA-cleared for non-diabetics', '14-day sensor life', 'MARD 7.8% accuracy', 'Time-in-range + trend analysis'],
    bestFor: 'Non-diabetics wanting metabolic insights without a prescription',
    affiliateUrl: '/go/dexcom-stelo',
    reviewSlug: 'wearables/best-continuous-glucose-monitors',
    reviewLabel: 'Read Full CGM Review',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&q=80',
  },

  // ─── MASSAGE & RECOVERY ───────────────────────────────────────────────
  {
    id: 'theragun-pro-6',
    name: 'Pro Gen 6',
    brand: 'Theragun',
    tagline: 'Professional percussive therapy — deepest amplitude available',
    category: 'Massage & Recovery',
    goals: ['Recovery', 'Inflammation'],
    evidenceLevel: 'Moderate',
    evidenceScore: 82,
    safetyScore: 97,
    popularityScore: 93,
    price: '$599',
    badge: 'Best Pick',
    summary: '16mm amplitude and 60 lbs stall force — the professional standard for percussive therapy. Rotating arm, OLED screen, Bluetooth app with 30+ guided routines.',
    keyBenefits: ['16mm amplitude (deepest available)', '60 lbs stall force', 'Rotating arm for hard-to-reach areas', 'OLED screen + 30+ app routines', '150 min battery (2 batteries)'],
    bestFor: 'Athletes and serious users wanting maximum depth and guidance',
    affiliateUrl: '/go/theragun-pro-6',
    reviewSlug: 'recovery/best-massage-guns-percussive-therapy',
    reviewLabel: 'Read Full Massage Gun Review',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&q=80',
  },
  {
    id: 'hypervolt-2-pro',
    name: 'Hypervolt 2 Pro',
    brand: 'Hyperice',
    tagline: 'Quietest premium massage gun — 55dB at full speed',
    category: 'Massage & Recovery',
    goals: ['Recovery', 'Inflammation'],
    evidenceLevel: 'Moderate',
    evidenceScore: 78,
    safetyScore: 97,
    popularityScore: 88,
    price: '$329',
    badge: 'Runner-Up',
    summary: 'The quietest high-end massage gun tested at 55dB. Pressure sensor guides optimal force, Bluetooth app integration, excellent ergonomics.',
    keyBenefits: ['Quietest device tested (55dB)', 'Pressure sensor feedback', '5 speeds + 5 attachments', 'Great balance & ergonomics'],
    bestFor: 'Home users who want quiet operation and smart guidance',
    affiliateUrl: '/go/hypervolt-2-pro',
    reviewSlug: 'recovery/best-massage-guns-percussive-therapy',
    reviewLabel: 'Read Full Massage Gun Review',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&q=80',
  },

  // ─── SUPPLEMENTS ──────────────────────────────────────────────────────
  {
    id: 'nmn',
    name: 'NMN Pro',
    brand: 'ProHealth Longevity',
    tagline: 'Best-tested NMN — 500mg sublingual, third-party verified',
    category: 'NAD+ Precursors',
    goals: ['Longevity', 'Energy', 'Cognitive'],
    evidenceLevel: 'Moderate',
    evidenceScore: 72,
    safetyScore: 92,
    popularityScore: 95,
    price: '$67.99',
    badge: 'Best Pick',
    summary: 'ProHealth Longevity NMN Pro is independently third-party tested and offers a sublingual delivery option for improved bioavailability. 500mg pure NMN per serving.',
    keyBenefits: ['Third-party purity tested', '500mg NMN per serving', 'Sublingual option available', 'No fillers or additives'],
    bestFor: 'NAD+ restoration and longevity supplementation',
    affiliateUrl: '/go/prohealth-nmn',
    reviewSlug: 'supplements/best-nmn-supplements-2024',
    reviewLabel: 'Read Full NMN Review',
    dosage: '250–500mg/day',
    timing: 'Morning',
    stacksWith: ['tmg', 'resveratrol', 'coq10'],
    studyCount: 42,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'nr-tru-niagen',
    name: 'Tru Niagen',
    brand: 'ChromaDex',
    tagline: 'Most studied NR — patented formula with 38+ clinical trials',
    category: 'NAD+ Precursors',
    goals: ['Longevity', 'Energy'],
    evidenceLevel: 'Moderate',
    evidenceScore: 69,
    safetyScore: 95,
    popularityScore: 88,
    price: '$47.99',
    badge: 'Runner-Up',
    summary: 'Tru Niagen uses patented nicotinamide riboside (NR) with more published human clinical trials than any other NAD+ precursor. The safe, well-studied choice.',
    keyBenefits: ['Patented Niagen NR formula', '38+ human clinical trials', 'No fishy taste', 'Well-tolerated'],
    bestFor: 'Those who prefer more human trial data over NMN',
    affiliateUrl: '/go/tru-niagen',
    reviewSlug: 'supplements/best-nmn-supplements-2024',
    reviewLabel: 'Read NMN vs NR Review',
    dosage: '300–600mg/day',
    timing: 'Morning',
    studyCount: 38,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'omega3-carlson',
    name: 'Elite Omega-3',
    brand: 'Carlson',
    tagline: 'IFOS 5-star rated — 1600mg EPA+DHA, Friend of the Sea certified',
    category: 'Omega Fatty Acids',
    goals: ['Cardiovascular', 'Inflammation', 'Cognitive', 'Longevity'],
    evidenceLevel: 'Strong',
    evidenceScore: 88,
    safetyScore: 95,
    popularityScore: 92,
    price: '$34.99',
    badge: 'Best Pick',
    summary: 'Carlson Elite Omega-3 is IFOS 5-star certified — the highest purity standard for fish oil. 1600mg EPA+DHA per serving from Friend-of-the-Sea certified sources.',
    keyBenefits: ['IFOS 5-star purity certified', '1600mg EPA+DHA per serving', 'Friend-of-the-Sea certified', 'No fishy aftertaste (lemon flavour)'],
    bestFor: 'Daily cardiovascular and anti-inflammatory omega-3 supplementation',
    affiliateUrl: '/go/carlson-omega3',
    reviewSlug: 'supplements/best-omega-3-fish-oil',
    reviewLabel: 'Read Full Omega-3 Review',
    dosage: '2–4g EPA+DHA daily',
    timing: 'With meals',
    studyCount: 843,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'creatine-mono',
    name: 'Creatine Monohydrate',
    brand: 'Thorne',
    tagline: 'Most evidence-backed supplement in sports science — 5g/day',
    category: 'Mitochondrial Support',
    goals: ['Strength & Muscle', 'Cognitive', 'Energy', 'Longevity'],
    evidenceLevel: 'Strong',
    evidenceScore: 91,
    safetyScore: 98,
    popularityScore: 95,
    price: '$39.99',
    badge: "Editor's Choice",
    summary: "Creatine monohydrate has 500+ studies supporting its efficacy. Thorne's pharmaceutical-grade NSF-certified version is clean, effective, and trusted by professional athletes.",
    keyBenefits: ['500+ supporting studies', 'NSF Certified for Sport', 'No loading phase needed', 'Cognitive + physical benefits', 'Pharmaceutical-grade manufacturing'],
    bestFor: 'Everyone over 30 — the most evidence-backed supplement for longevity beyond the gym',
    affiliateUrl: '/go/thorne-creatine',
    dosage: '3–5g/day',
    timing: 'Anytime — consistency matters',
    studyCount: 500,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'magnesium-glycinate',
    name: 'Magnesium Glycinate',
    brand: 'Pure Encapsulations',
    tagline: 'Best-absorbed magnesium — sleep, recovery, cardiovascular',
    category: 'Vitamins & Minerals',
    goals: ['Sleep', 'Cardiovascular', 'Recovery', 'Cognitive'],
    evidenceLevel: 'Strong',
    evidenceScore: 82,
    safetyScore: 97,
    popularityScore: 93,
    price: '$28.99',
    badge: 'Best Pick',
    summary: 'Magnesium glycinate has the best absorption-to-tolerance ratio of all magnesium forms. Pure Encapsulations is hypoallergenic and free from common fillers.',
    keyBenefits: ['Glycinate form — best absorbed', 'Hypoallergenic formula', 'No GI side effects', 'Supports sleep onset and quality'],
    bestFor: 'Sleep quality, muscle relaxation, and cardiovascular health',
    affiliateUrl: '/go/pure-mag-glycinate',
    dosage: '200–400mg elemental',
    timing: 'Evening, 1 hour before bed',
    studyCount: 289,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'vitamin-d3-k2',
    name: 'Vitamin D3+K2',
    brand: 'Thorne',
    tagline: 'D3 with MK-7 K2 — bone, immune, cardiovascular support',
    category: 'Vitamins & Minerals',
    goals: ['Longevity', 'Cardiovascular', 'Inflammation'],
    evidenceLevel: 'Strong',
    evidenceScore: 84,
    safetyScore: 90,
    popularityScore: 94,
    price: '$24.99',
    badge: 'Best Pick',
    summary: "D3 paired with MK-7 K2 ensures calcium goes to bones not arteries. Thorne's 1000 IU D3 + 200mcg K2 combination is the gold standard for supplementation.",
    keyBenefits: ['D3 + MK-7 K2 combination', 'Ensures proper calcium direction', 'NSF Certified', 'Optimal absorption with fat'],
    bestFor: 'Correcting vitamin D deficiency (>40% of adults) safely',
    affiliateUrl: '/go/thorne-d3k2',
    dosage: '2,000–5,000 IU D3 daily',
    timing: 'Morning with a fatty meal',
    studyCount: 612,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'coq10-ubiquinol',
    name: 'Ubiquinol CoQ10',
    brand: 'Jarrow Formulas',
    tagline: 'Ubiquinol form — superior absorption for mitochondrial energy',
    category: 'Mitochondrial Support',
    goals: ['Energy', 'Cardiovascular', 'Longevity'],
    evidenceLevel: 'Moderate',
    evidenceScore: 74,
    safetyScore: 96,
    popularityScore: 85,
    price: '$42.99',
    badge: 'Best Pick',
    summary: 'Ubiquinol is the active, reduced form of CoQ10 with superior bioavailability — especially important over age 40 when conversion from ubiquinone declines.',
    keyBenefits: ['Ubiquinol form (better absorbed)', 'Essential for statin users', 'Declines with age — supplementation restores', 'Lipid-soluble antioxidant'],
    bestFor: 'People over 40, statin users, and those optimising mitochondrial function',
    affiliateUrl: '/go/jarrow-ubiquinol',
    dosage: '100–300mg/day',
    timing: 'With a fatty meal',
    studyCount: 156,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'ashwagandha-ksm66',
    name: 'KSM-66 Ashwagandha',
    brand: 'Ixoreal / KSM-66',
    tagline: 'Most studied ashwagandha extract — 67 clinical trials',
    category: 'Adaptogens',
    goals: ['Sleep', 'Recovery', 'Cognitive', 'Energy'],
    evidenceLevel: 'Moderate',
    evidenceScore: 71,
    safetyScore: 88,
    popularityScore: 92,
    price: '$22.99',
    badge: 'Best Pick',
    summary: 'KSM-66 is the most clinically studied ashwagandha extract. 67 peer-reviewed studies demonstrate cortisol reduction, sleep improvement, and testosterone support.',
    keyBenefits: ['67 clinical trials (most studied)', 'Reduces cortisol up to 30%', 'Improves sleep onset and quality', 'Testosterone + strength support'],
    bestFor: 'Stress management, sleep improvement, and cortisol reduction',
    affiliateUrl: '/go/ksm66-ashwagandha',
    dosage: '300–600mg KSM-66',
    timing: 'Evening (or split AM/PM)',
    studyCount: 67,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },
  {
    id: 'berberine-hcl',
    name: 'Berberine HCl',
    brand: 'Thorne',
    tagline: "Nature's metformin — AMPK activator with cardiovascular benefits",
    category: 'Mitochondrial Support',
    goals: ['Longevity', 'Cardiovascular', 'Metabolic Health'],
    evidenceLevel: 'Moderate',
    evidenceScore: 76,
    safetyScore: 80,
    popularityScore: 84,
    price: '$35.99',
    badge: 'Best Pick',
    summary: 'Berberine activates AMPK (the same pathway as metformin), improving insulin sensitivity and cardiovascular markers. Multiple RCTs show meaningful glycaemic and lipid benefits.',
    keyBenefits: ['AMPK activator', 'Improves insulin sensitivity', 'Lowers LDL and triglycerides', 'Multiple RCTs in humans'],
    bestFor: 'Metabolic health, blood glucose management, and longevity signalling',
    affiliateUrl: '/go/thorne-berberine',
    dosage: '500mg 2–3x/day with meals',
    timing: 'With meals',
    studyCount: 89,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
  },

  // ─── BLOOD DIAGNOSTICS ────────────────────────────────────────────────
  {
    id: 'function-health',
    name: 'Function Health',
    brand: 'Function',
    tagline: '160+ biomarkers — the most comprehensive DTC blood panel',
    category: 'Blood & Diagnostics',
    goals: ['Longevity', 'Cardiovascular', 'Metabolic Health'],
    evidenceLevel: 'Strong',
    evidenceScore: 94,
    safetyScore: 99,
    popularityScore: 88,
    price: '$499/year',
    badge: 'Best Pick',
    summary: 'Function Health offers 160+ biomarkers including ApoB, Lp(a), fasting insulin, homocysteine, and TMAO — more than most concierge practices. Co-founded by Dr. Mark Hyman.',
    keyBenefits: ['160+ biomarkers', 'Includes ApoB, Lp(a), fasting insulin', 'Physician-reviewed results', 'Year-over-year trending', '2 panels per year included'],
    bestFor: 'Comprehensive annual health baseline and longevity tracking',
    affiliateUrl: '/go/function-health',
    reviewSlug: 'diagnostics/best-at-home-blood-tests-2024',
    reviewLabel: 'Read Full Blood Test Review',
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&q=80',
  },
  {
    id: 'insidetracker',
    name: 'InsideTracker Ultimate',
    brand: 'InsideTracker',
    tagline: 'Athlete-optimised blood + DNA testing with food recommendations',
    category: 'Blood & Diagnostics',
    goals: ['Longevity', 'Cardiovascular', 'Strength & Muscle'],
    evidenceLevel: 'Strong',
    evidenceScore: 86,
    safetyScore: 99,
    popularityScore: 84,
    price: '$299–699',
    badge: 'Runner-Up',
    summary: 'InsideTracker optimises for athletic performance and longevity. Strong mobile app with personalised food and supplement recommendations based on your bloodwork and DNA.',
    keyBenefits: ['Athlete-optimised biomarkers', 'DNA + blood combination available', 'Personalised food recommendations', 'Optimal zones not just normal ranges'],
    bestFor: 'Athletes wanting bloodwork integrated with performance optimisation',
    affiliateUrl: '/go/insidetracker',
    reviewSlug: 'diagnostics/best-at-home-blood-tests-2024',
    reviewLabel: 'Read Full Blood Test Review',
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&q=80',
  },
]

// ─── Helper functions ──────────────────────────────────────────────────────
export function getProductById(id: string): Product | null {
  return products.find(p => p.id === id) ?? null
}

export function getProductsByCategory(cat: ProductCategory): Product[] {
  return products.filter(p => p.category === cat)
}

export function getProductsByGoal(goal: Goal): Product[] {
  return products.filter(p => p.goals.includes(goal))
}

export const allCategories: ProductCategory[] = [
  'Red Light Therapy',
  'Infrared Saunas',
  'Cold Plunge & Ice Baths',
  'Fitness Trackers & HRV',
  'Continuous Glucose Monitors',
  'Massage & Recovery',
  'NAD+ Precursors',
  'Antioxidants & Senolytics',
  'Adaptogens',
  'Omega Fatty Acids',
  'Vitamins & Minerals',
  'Mitochondrial Support',
  'Blood & Diagnostics',
]

export const categoryGroups: { label: string; categories: ProductCategory[] }[] = [
  { label: 'Recovery Devices', categories: ['Red Light Therapy', 'Infrared Saunas', 'Cold Plunge & Ice Baths', 'Massage & Recovery'] },
  { label: 'Wearables & Tracking', categories: ['Fitness Trackers & HRV', 'Continuous Glucose Monitors', 'Blood & Diagnostics'] },
  { label: 'Supplements', categories: ['NAD+ Precursors', 'Antioxidants & Senolytics', 'Adaptogens', 'Omega Fatty Acids', 'Vitamins & Minerals', 'Mitochondrial Support'] },
]

export const evidenceBadgeColors: Record<EvidenceLevel, string> = {
  Strong: 'bg-green/10 text-green-bright border-green/25',
  Moderate: 'bg-amber/10 text-amber border-amber/25',
  Emerging: 'bg-blue-500/10 text-blue-500 border-blue-500/25',
  Weak: 'bg-red-500/10 text-red-400 border-red-500/25',
}

export const badgeColors: Record<string, string> = {
  'Best Pick': 'bg-green/10 text-green-bright border-green/25',
  'Runner-Up': 'bg-amber/10 text-amber border-amber/25',
  'Budget': 'bg-blue-500/10 text-blue-500 border-blue-500/20',
  "Editor's Choice": 'bg-purple-500/10 text-purple-400 border-purple-500/20',
  'Premium': 'bg-amber/10 text-amber border-amber/20',
}
