/**
 * 410 Gone support for Cloudflare Pages. `_redirects` cannot return 410 (Pages supports 200/301/302/303/307/308/404 only),
 * so intentionally removed pages with no replacement are listed in `gone.txt` (one path per line, # comments allowed)
 * and answered by a Pages Function. Google treats 410 like 404 but drops the URL from the index somewhat faster
 * (developers.google.com/search/docs/crawling-indexing/http-network-errors). Use a 301 whenever a real replacement exists.
 * `_routes.json` (generated by `pnpm seo:gone <site>`) limits the Function to /go/* and these paths, so normal pages never invoke it.
 */
export const parseGone = (text: string): string[] =>
  [...new Set(text.split(/\r?\n/).map((l) => l.replace(/#.*/, "").trim()).filter(Boolean))].sort();

export const isGone = (pathname: string, gone: Iterable<string>) => {
  const set = new Set(gone);
  const p = pathname.replace(/\/+$/, "") || "/";
  return set.has(pathname) || set.has(p) || set.has(p + "/");
};

export function goneResponse(): Response {
  return new Response(
    '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="robots" content="noindex"><title>Gone</title></head><body><h1>This page has been permanently removed.</h1><p><a href="/">Go to the home page</a></p></body></html>',
    { status: 410, headers: { "content-type": "text/html; charset=utf-8", "x-robots-tag": "noindex", "cache-control": "public, max-age=3600" } },
  );
}

/** `_routes.json` and `_redirects` match literally, so a gone path must be routed in both slash forms (/x and /x/). Files and wildcards stay as they are. */
export const routeForms = (g: string): string[] => {
  if (g.includes("*") || g === "/" || /\.[a-z0-9]+$/i.test(g.split("/").pop() ?? "")) return [g];
  const bare = g.replace(/\/+$/, "");
  return [bare, bare + "/"];
};

/** `_routes.json` content: Functions run only for these routes. Cloudflare allows at most 100 include/exclude rules. */
export function routesJson(gone: string[], extraInclude: string[] = ["/go/*"]) {
  const include = [...new Set([...extraInclude, ...gone.flatMap(routeForms)])];
  if (include.length > 100) throw new Error(`_routes.json limit is 100 rules, got ${include.length}: group gone paths with wildcards (each path takes two rules, one per slash form)`);
  return { version: 1, include, exclude: [] as string[] };
}
